//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class AbstractDynamicalModel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal AbstractDynamicalModel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractDynamicalModel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbstractDynamicalModel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_AbstractDynamicalModel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void resetToInitialState() {
    UtilsPINVOKE.AbstractDynamicalModel_resetToInitialState(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getNumDegreeOfFreedom() {
    uint ret = UtilsPINVOKE.AbstractDynamicalModel_getNumDegreeOfFreedom(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setNumDegreeOfFreedom(uint nDof) {
    UtilsPINVOKE.AbstractDynamicalModel_setNumDegreeOfFreedom(swigCPtr, nDof);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t getTaskGraph() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t(UtilsPINVOKE.AbstractDynamicalModel_getTaskGraph(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DynamicalModelType getType() {
    DynamicalModelType ret = (DynamicalModelType)UtilsPINVOKE.AbstractDynamicalModel_getType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void updatePhysicsGeometry() {
    UtilsPINVOKE.AbstractDynamicalModel_updatePhysicsGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setTimeStep(double timeStep) {
    UtilsPINVOKE.AbstractDynamicalModel_setTimeStep(swigCPtr, timeStep);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setModelGeometry(Geometry geometry) {
    UtilsPINVOKE.AbstractDynamicalModel_setModelGeometry(swigCPtr, Geometry.getCPtr(geometry));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isGeometryValid(Geometry geometry) {
    bool ret = UtilsPINVOKE.AbstractDynamicalModel_isGeometryValid(swigCPtr, Geometry.getCPtr(geometry));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Geometry getModelGeometry() {
    global::System.IntPtr cPtr = UtilsPINVOKE.AbstractDynamicalModel_getModelGeometry(swigCPtr);
    Geometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new Geometry(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getTimeStep() {
    double ret = UtilsPINVOKE.AbstractDynamicalModel_getTimeStep(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool initialize() {
    bool ret = UtilsPINVOKE.AbstractDynamicalModel_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void initGraphEdges() {
    UtilsPINVOKE.AbstractDynamicalModel_initGraphEdges(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setTimeStepSizeType(TimeSteppingType type) {
    UtilsPINVOKE.AbstractDynamicalModel_setTimeStepSizeType(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public TimeSteppingType getTimeStepSizeType() {
    TimeSteppingType ret = (TimeSteppingType)UtilsPINVOKE.AbstractDynamicalModel_getTimeStepSizeType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum StateUpdateType {
    Displacement,
    Velocity,
    DeltaDisplacement,
    DeltaVelocity,
    None
  }

}

}
