//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class AnalyticalGeometry : ImplicitGeometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal AnalyticalGeometry(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.AnalyticalGeometry_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AnalyticalGeometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_AnalyticalGeometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override void print() {
    UtilsPINVOKE.AnalyticalGeometry_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getPosition(Geometry.DataType type) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.AnalyticalGeometry_getPosition__SWIG_0(swigCPtr, (int)type), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getPosition() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.AnalyticalGeometry_getPosition__SWIG_1(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPosition(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t p) {
    UtilsPINVOKE.AnalyticalGeometry_setPosition__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(p));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPosition(double x, double y, double z) {
    UtilsPINVOKE.AnalyticalGeometry_setPosition__SWIG_1(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__QuaternionT_double_t getOrientation(Geometry.DataType type) {
    SWIGTYPE_p_Eigen__QuaternionT_double_t ret = new SWIGTYPE_p_Eigen__QuaternionT_double_t(UtilsPINVOKE.AnalyticalGeometry_getOrientation__SWIG_0(swigCPtr, (int)type), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__QuaternionT_double_t getOrientation() {
    SWIGTYPE_p_Eigen__QuaternionT_double_t ret = new SWIGTYPE_p_Eigen__QuaternionT_double_t(UtilsPINVOKE.AnalyticalGeometry_getOrientation__SWIG_1(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOrientation(SWIGTYPE_p_Eigen__QuaternionT_double_t r) {
    UtilsPINVOKE.AnalyticalGeometry_setOrientation(swigCPtr, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(r));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getFunctionValue(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t arg0) {
    double ret = UtilsPINVOKE.AnalyticalGeometry_getFunctionValue(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(arg0));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updatePostTransformData() {
    UtilsPINVOKE.AnalyticalGeometry_updatePostTransformData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
