//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class ArcNeedle : Needle {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ArcNeedle(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.ArcNeedle_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArcNeedle obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_ArcNeedle(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ArcNeedle(string name) : this(UtilsPINVOKE.new_ArcNeedle__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public ArcNeedle() : this(UtilsPINVOKE.new_ArcNeedle__SWIG_1(), true) {
  }

  public void setArc(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t arcCenter, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t arcBasis, double arcRadius, double beginRad, double endRad) {
    UtilsPINVOKE.ArcNeedle_setArc(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(arcCenter), SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(arcBasis), arcRadius, beginRad, endRad);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_3_t getArcBasis() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_3_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_3_t(UtilsPINVOKE.ArcNeedle_getArcBasis(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getArcCenter() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.ArcNeedle_getArcCenter(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getBeginRad() {
    double ret = UtilsPINVOKE.ArcNeedle_getBeginRad(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getEndRad() {
    double ret = UtilsPINVOKE.ArcNeedle_getEndRad(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getArcRadius() {
    double ret = UtilsPINVOKE.ArcNeedle_getArcRadius(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
