//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class AssertMessage : LogMessageBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AssertMessage(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.AssertMessage_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AssertMessage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AssertMessage obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_AssertMessage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public AssertMessage(Logger logger) : this(UtilsPINVOKE.new_AssertMessage__SWIG_0(Logger.getCPtr(logger)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public AssertMessage(SWIGTYPE_p_std__unique_ptrT_imstk__LoggerSynchronous_t logger) : this(UtilsPINVOKE.new_AssertMessage__SWIG_1(SWIGTYPE_p_std__unique_ptrT_imstk__LoggerSynchronous_t.getCPtr(logger)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void setFailureCallback(SWIGTYPE_p_f_r_q_const__std__string__void callback) {
    UtilsPINVOKE.AssertMessage_setFailureCallback(SWIGTYPE_p_f_r_q_const__std__string__void.getCPtr(callback));
  }

  public static SWIGTYPE_p_f_r_q_const__std__string__void getFailureCallback() {
    global::System.IntPtr cPtr = UtilsPINVOKE.AssertMessage_getFailureCallback();
    SWIGTYPE_p_f_r_q_const__std__string__void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_r_q_const__std__string__void(cPtr, false);
    return ret;
  }

  public static void setFailureBehaviorToThrow() {
    UtilsPINVOKE.AssertMessage_setFailureBehaviorToThrow();
  }

  public static void setFailureBehaviorToDeath() {
    UtilsPINVOKE.AssertMessage_setFailureBehaviorToDeath();
  }

}

}
