//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class BackwardEuler : TimeIntegrator {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal BackwardEuler(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.BackwardEuler_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BackwardEuler obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_BackwardEuler(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public BackwardEuler(double dT) : this(UtilsPINVOKE.new_BackwardEuler__SWIG_0(dT), true) {
  }

  public BackwardEuler() : this(UtilsPINVOKE.new_BackwardEuler__SWIG_1(), true) {
  }

  public override void updateStateGivenDv(FeDeformBodyState prevState, FeDeformBodyState currentState, SWIGTYPE_p_Eigen__VectorXd dV) {
    UtilsPINVOKE.BackwardEuler_updateStateGivenDv(swigCPtr, FeDeformBodyState.getCPtr(prevState), FeDeformBodyState.getCPtr(currentState), SWIGTYPE_p_Eigen__VectorXd.getCPtr(dV));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateStateGivenDu(FeDeformBodyState prevState, FeDeformBodyState currentState, SWIGTYPE_p_Eigen__VectorXd dU) {
    UtilsPINVOKE.BackwardEuler_updateStateGivenDu(swigCPtr, FeDeformBodyState.getCPtr(prevState), FeDeformBodyState.getCPtr(currentState), SWIGTYPE_p_Eigen__VectorXd.getCPtr(dU));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateStateGivenV(FeDeformBodyState prevState, FeDeformBodyState currentState, SWIGTYPE_p_Eigen__VectorXd v) {
    UtilsPINVOKE.BackwardEuler_updateStateGivenV(swigCPtr, FeDeformBodyState.getCPtr(prevState), FeDeformBodyState.getCPtr(currentState), SWIGTYPE_p_Eigen__VectorXd.getCPtr(v));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updateStateGivenU(FeDeformBodyState prevState, FeDeformBodyState currentState, SWIGTYPE_p_Eigen__VectorXd u) {
    UtilsPINVOKE.BackwardEuler_updateStateGivenU(swigCPtr, FeDeformBodyState.getCPtr(prevState), FeDeformBodyState.getCPtr(currentState), SWIGTYPE_p_Eigen__VectorXd.getCPtr(u));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
