//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Camera : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Camera(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Camera obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Camera() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_Camera(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Camera() : this(UtilsPINVOKE.new_Camera(), true) {
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_4_4_t getView() {
    SWIGTYPE_p_Eigen__MatrixT_double_4_4_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_4_4_t(UtilsPINVOKE.Camera_getView(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_4_4_t getHMDView() {
    SWIGTYPE_p_Eigen__MatrixT_double_4_4_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_4_4_t(UtilsPINVOKE.Camera_getHMDView(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_4_4_t getProj() {
    SWIGTYPE_p_Eigen__MatrixT_double_4_4_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_4_4_t(UtilsPINVOKE.Camera_getProj(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_4_4_t getInvView() {
    SWIGTYPE_p_Eigen__MatrixT_double_4_4_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_4_4_t(UtilsPINVOKE.Camera_getInvView(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setView(SWIGTYPE_p_Eigen__MatrixT_double_4_4_t view) {
    UtilsPINVOKE.Camera_setView(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(view));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getFieldOfView() {
    double ret = UtilsPINVOKE.Camera_getFieldOfView(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setFieldOfView(double fov) {
    UtilsPINVOKE.Camera_setFieldOfView(swigCPtr, fov);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setNearZ(double nearZ) {
    UtilsPINVOKE.Camera_setNearZ(swigCPtr, nearZ);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getNearZ() {
    double ret = UtilsPINVOKE.Camera_getNearZ(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setFarZ(double farZ) {
    UtilsPINVOKE.Camera_setFarZ(swigCPtr, farZ);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getFarZ() {
    double ret = UtilsPINVOKE.Camera_getFarZ(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void update() {
    UtilsPINVOKE.Camera_update(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getPosition() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Camera_getPosition(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPosition(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    UtilsPINVOKE.Camera_setPosition__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setPosition(double x, double y, double z) {
    UtilsPINVOKE.Camera_setPosition__SWIG_1(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getFocalPoint() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Camera_getFocalPoint(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setFocalPoint(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t focalPt) {
    UtilsPINVOKE.Camera_setFocalPoint__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(focalPt));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setFocalPoint(double x, double y, double z) {
    UtilsPINVOKE.Camera_setFocalPoint__SWIG_1(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getViewUp() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Camera_getViewUp(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getForward() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Camera_getForward(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getEyeRayDir(SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ndcPos) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Camera_getEyeRayDir(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(ndcPos)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setViewUp(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t up) {
    UtilsPINVOKE.Camera_setViewUp__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(up));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setViewUp(double x, double y, double z) {
    UtilsPINVOKE.Camera_setViewUp__SWIG_1(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void print() {
    UtilsPINVOKE.Camera_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
