//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Capsule : AnalyticalGeometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Capsule(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Capsule_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Capsule obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Capsule(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Capsule(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double radius, double length, SWIGTYPE_p_Eigen__QuaternionT_double_t orientation) : this(UtilsPINVOKE.new_Capsule__SWIG_0(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), radius, length, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orientation)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Capsule(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double radius, double length) : this(UtilsPINVOKE.new_Capsule__SWIG_1(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), radius, length), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Capsule(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double radius) : this(UtilsPINVOKE.new_Capsule__SWIG_2(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), radius), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Capsule(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) : this(UtilsPINVOKE.new_Capsule__SWIG_3(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Capsule() : this(UtilsPINVOKE.new_Capsule__SWIG_4(), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.Capsule_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.Capsule_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void print() {
    UtilsPINVOKE.Capsule_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getVolume() {
    double ret = UtilsPINVOKE.Capsule_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getRadius(Geometry.DataType type) {
    double ret = UtilsPINVOKE.Capsule_getRadius__SWIG_0(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getRadius() {
    double ret = UtilsPINVOKE.Capsule_getRadius__SWIG_1(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRadius(double r) {
    UtilsPINVOKE.Capsule_setRadius(swigCPtr, r);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getLength(Geometry.DataType type) {
    double ret = UtilsPINVOKE.Capsule_getLength__SWIG_0(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getLength() {
    double ret = UtilsPINVOKE.Capsule_getLength__SWIG_1(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLength(double l) {
    UtilsPINVOKE.Capsule_setLength(swigCPtr, l);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getFunctionValue(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t x) {
    double ret = UtilsPINVOKE.Capsule_getFunctionValue(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(x));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t min, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t max, double paddingPercent) {
    UtilsPINVOKE.Capsule_computeBoundingBox(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(min), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(max), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updatePostTransformData() {
    UtilsPINVOKE.Capsule_updatePostTransformData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
