//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CellIndexElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CellIndexElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CellIndexElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CellIndexElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CellIndexElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_CellIndexElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_int ids {
    set {
      UtilsPINVOKE.CellIndexElement_ids_set(swigCPtr, SWIGTYPE_p_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.CellIndexElement_ids_get(swigCPtr);
      SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
      return ret;
    } 
  }

  public int parentId {
    set {
      UtilsPINVOKE.CellIndexElement_parentId_set(swigCPtr, value);
    } 
    get {
      int ret = UtilsPINVOKE.CellIndexElement_parentId_get(swigCPtr);
      return ret;
    } 
  }

  public int idCount {
    set {
      UtilsPINVOKE.CellIndexElement_idCount_set(swigCPtr, value);
    } 
    get {
      int ret = UtilsPINVOKE.CellIndexElement_idCount_get(swigCPtr);
      return ret;
    } 
  }

  public byte cellType {
    set {
      UtilsPINVOKE.CellIndexElement_cellType_set(swigCPtr, value);
    } 
    get {
      byte ret = UtilsPINVOKE.CellIndexElement_cellType_get(swigCPtr);
      return ret;
    } 
  }

  public CellIndexElement() : this(UtilsPINVOKE.new_CellIndexElement(), true) {
  }

}

}
