//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CellVertexElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CellVertexElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CellVertexElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CellVertexElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CellVertexElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_CellVertexElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pts {
    set {
      UtilsPINVOKE.CellVertexElement_pts_set(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.CellVertexElement_pts_get(swigCPtr);
      SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(cPtr, false);
      return ret;
    } 
  }

  public int size {
    set {
      UtilsPINVOKE.CellVertexElement_size_set(swigCPtr, value);
    } 
    get {
      int ret = UtilsPINVOKE.CellVertexElement_size_get(swigCPtr);
      return ret;
    } 
  }

  public CellVertexElement() : this(UtilsPINVOKE.new_CellVertexElement(), true) {
  }

}

}
