//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CellMesh8 : AbstractCellMesh {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal CellMesh8(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.CellMesh8_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CellMesh8 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_CellMesh8(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CellMesh8() : this(UtilsPINVOKE.new_CellMesh8(), true) {
  }

  public void initialize(VecDataArray3d vertices, SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t indices) {
    UtilsPINVOKE.CellMesh8_initialize(swigCPtr, VecDataArray3d.getCPtr(vertices), SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getCellVertexCount() {
    int ret = UtilsPINVOKE.CellMesh8_getCellVertexCount(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void clear() {
    UtilsPINVOKE.CellMesh8_clear(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeVertexToCellMap() {
    UtilsPINVOKE.CellMesh8_computeVertexToCellMap(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeVertexNeighbors() {
    UtilsPINVOKE.CellMesh8_computeVertexNeighbors(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_Eigen__VectorT_double_8_t computeBarycentricWeights(int arg0, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t arg1) {
    SWIGTYPE_p_Eigen__VectorT_double_8_t ret = new SWIGTYPE_p_Eigen__VectorT_double_8_t(UtilsPINVOKE.CellMesh8_computeBarycentricWeights(swigCPtr, arg0, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(arg1)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t computeWorldPosition(int cellId, SWIGTYPE_p_Eigen__MatrixT_double_8_1_t bary) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.CellMesh8_computeWorldPosition(swigCPtr, cellId, SWIGTYPE_p_Eigen__MatrixT_double_8_1_t.getCPtr(bary)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override AbstractDataArray getAbstractCells() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CellMesh8_getAbstractCells(swigCPtr);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCells(SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t indices) {
    UtilsPINVOKE.CellMesh8_setCells(swigCPtr, SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t getCells() {
    SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__VecDataArrayT_int_8_t_t(UtilsPINVOKE.CellMesh8_getCells(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int getNumCells() {
    int ret = UtilsPINVOKE.CellMesh8_getNumCells(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly int CellVertexCount = UtilsPINVOKE.CellMesh8_CellVertexCount_get();
}

}
