//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CellMesh2 : AbstractCellMesh {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal CellMesh2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.CellMesh2_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CellMesh2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_CellMesh2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CellMesh2() : this(UtilsPINVOKE.new_CellMesh2(), true) {
  }

  public void initialize(VecDataArray3d vertices, VecDataArray2i indices) {
    UtilsPINVOKE.CellMesh2_initialize(swigCPtr, VecDataArray3d.getCPtr(vertices), VecDataArray2i.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getCellVertexCount() {
    int ret = UtilsPINVOKE.CellMesh2_getCellVertexCount(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void clear() {
    UtilsPINVOKE.CellMesh2_clear(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeVertexToCellMap() {
    UtilsPINVOKE.CellMesh2_computeVertexToCellMap(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeVertexNeighbors() {
    UtilsPINVOKE.CellMesh2_computeVertexNeighbors(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_Eigen__VectorT_double_2_t computeBarycentricWeights(int arg0, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t arg1) {
    SWIGTYPE_p_Eigen__VectorT_double_2_t ret = new SWIGTYPE_p_Eigen__VectorT_double_2_t(UtilsPINVOKE.CellMesh2_computeBarycentricWeights(swigCPtr, arg0, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(arg1)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t computeWorldPosition(int cellId, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t bary) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.CellMesh2_computeWorldPosition(swigCPtr, cellId, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(bary)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override AbstractDataArray getAbstractCells() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CellMesh2_getAbstractCells(swigCPtr);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCells(VecDataArray2i indices) {
    UtilsPINVOKE.CellMesh2_setCells(swigCPtr, VecDataArray2i.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecDataArray2i getCells() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CellMesh2_getCells(swigCPtr);
    VecDataArray2i ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecDataArray2i(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int getNumCells() {
    int ret = UtilsPINVOKE.CellMesh2_getNumCells(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly int CellVertexCount = UtilsPINVOKE.CellMesh2_CellVertexCount_get();
}

}
