//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CollisionInteraction : SceneObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal CollisionInteraction(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.CollisionInteraction_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollisionInteraction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_CollisionInteraction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public void setCollisionDetection(CollisionDetectionAlgorithm colDetect) {
    UtilsPINVOKE.CollisionInteraction_setCollisionDetection(swigCPtr, CollisionDetectionAlgorithm.getCPtr(colDetect));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCollisionHandlingA(CollisionHandling colHandlingA) {
    UtilsPINVOKE.CollisionInteraction_setCollisionHandlingA(swigCPtr, CollisionHandling.getCPtr(colHandlingA));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCollisionHandlingB(CollisionHandling colHandlingB) {
    UtilsPINVOKE.CollisionInteraction_setCollisionHandlingB(swigCPtr, CollisionHandling.getCPtr(colHandlingB));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setCollisionHandlingAB(CollisionHandling colHandlingAB) {
    UtilsPINVOKE.CollisionInteraction_setCollisionHandlingAB(swigCPtr, CollisionHandling.getCPtr(colHandlingAB));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public CollisionDetectionAlgorithm getCollisionDetection() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CollisionInteraction_getCollisionDetection(swigCPtr);
    CollisionDetectionAlgorithm ret = (cPtr == global::System.IntPtr.Zero) ? null : new CollisionDetectionAlgorithm(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollisionHandling getCollisionHandlingA() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CollisionInteraction_getCollisionHandlingA(swigCPtr);
    CollisionHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new CollisionHandling(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollisionHandling getCollisionHandlingB() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CollisionInteraction_getCollisionHandlingB(swigCPtr);
    CollisionHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new CollisionHandling(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollisionHandling getCollisionHandlingAB() {
    global::System.IntPtr cPtr = UtilsPINVOKE.CollisionInteraction_getCollisionHandlingAB(swigCPtr);
    CollisionHandling ret = (cPtr == global::System.IntPtr.Zero) ? null : new CollisionHandling(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getCollisionDetectionNode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.CollisionInteraction_getCollisionDetectionNode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getCollisionHandlingANode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.CollisionInteraction_getCollisionHandlingANode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getCollisionHandlingBNode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.CollisionInteraction_getCollisionHandlingBNode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void updateCollisionGeometry() {
    UtilsPINVOKE.CollisionInteraction_updateCollisionGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setEnabled(bool enabled) {
    UtilsPINVOKE.CollisionInteraction_setEnabled(swigCPtr, enabled);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool getEnabled() {
    bool ret = UtilsPINVOKE.CollisionInteraction_getEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void visualUpdate() {
    UtilsPINVOKE.CollisionInteraction_visualUpdate(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
