//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CompositeImplicitGeometry : ImplicitGeometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal CompositeImplicitGeometry(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.CompositeImplicitGeometry_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CompositeImplicitGeometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_CompositeImplicitGeometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CompositeImplicitGeometry() : this(UtilsPINVOKE.new_CompositeImplicitGeometry(), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.CompositeImplicitGeometry_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.CompositeImplicitGeometry_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double getFunctionValue(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    double ret = UtilsPINVOKE.CompositeImplicitGeometry_getFunctionValue(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addImplicitGeometry(ImplicitGeometry geometry, CompositeImplicitGeometry.GeometryBoolType type) {
    UtilsPINVOKE.CompositeImplicitGeometry_addImplicitGeometry(swigCPtr, ImplicitGeometry.getCPtr(geometry), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public enum GeometryBoolType {
    Intersection,
    Difference,
    Union
  }

}

}
