//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class CompoundGeometry : Geometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal CompoundGeometry(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.CompoundGeometry_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CompoundGeometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_CompoundGeometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.CompoundGeometry_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.CompoundGeometry_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void add(AnalyticalGeometry geometry) {
    UtilsPINVOKE.CompoundGeometry_add(swigCPtr, AnalyticalGeometry.getCPtr(geometry));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setLocalTransform(uint index, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t transform) {
    UtilsPINVOKE.CompoundGeometry_setLocalTransform(swigCPtr, index, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(transform));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint count() {
    uint ret = UtilsPINVOKE.CompoundGeometry_count(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Geometry get(uint index) {
    global::System.IntPtr cPtr = UtilsPINVOKE.CompoundGeometry_get(swigCPtr, index);
    Geometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new Geometry(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void print() {
    UtilsPINVOKE.CompoundGeometry_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getVolume() {
    double ret = UtilsPINVOKE.CompoundGeometry_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner, double paddingPercent) {
    UtilsPINVOKE.CompoundGeometry_computeBoundingBox__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner) {
    UtilsPINVOKE.CompoundGeometry_computeBoundingBox__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getCenter() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.CompoundGeometry_getCenter(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool isMesh() {
    bool ret = UtilsPINVOKE.CompoundGeometry_isMesh(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updatePostTransformData() {
    UtilsPINVOKE.CompoundGeometry_updatePostTransformData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void applyTransform(SWIGTYPE_p_Eigen__MatrixT_double_4_4_t arg0) {
    UtilsPINVOKE.CompoundGeometry_applyTransform(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(arg0));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public CompoundGeometry() : this(UtilsPINVOKE.new_CompoundGeometry(), true) {
  }

}

}
