//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DataArrayi : AbstractDataArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DataArrayi(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DataArrayi_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataArrayi obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DataArrayi(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DataArrayi() : this(UtilsPINVOKE.new_DataArrayi__SWIG_0(), true) {
  }

  public DataArrayi(int size) : this(UtilsPINVOKE.new_DataArrayi__SWIG_1(size), true) {
  }

  public DataArrayi(DataArrayi other) : this(UtilsPINVOKE.new_DataArrayi__SWIG_2(DataArrayi.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void resize(int size) {
    UtilsPINVOKE.DataArrayi_resize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void fill(int val) {
    UtilsPINVOKE.DataArrayi_fill(swigCPtr, val);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void squeeze() {
    UtilsPINVOKE.DataArrayi_squeeze(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(int val) {
    UtilsPINVOKE.DataArrayi_push_back__SWIG_0(swigCPtr, val);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(SWIGTYPE_p_int val) {
    UtilsPINVOKE.DataArrayi_push_back__SWIG_1(swigCPtr, SWIGTYPE_p_int.swigRelease(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator begin() {
    SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator ret = new SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator(UtilsPINVOKE.DataArrayi_begin(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator end() {
    SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator ret = new SWIGTYPE_p_imstk__DataArrayT_int_t__const_iterator(UtilsPINVOKE.DataArrayi_end(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void reserve(int capacity) {
    UtilsPINVOKE.DataArrayi_reserve(swigCPtr, capacity);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_int getPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayi_getPointer(swigCPtr);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SWIGTYPE_p_void getVoidPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayi_getVoidPointer(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_int setValue(uint pos) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(UtilsPINVOKE.DataArrayi_setValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getValue(uint pos) {
    int ret = UtilsPINVOKE.DataArrayi_getValue(swigCPtr, pos);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_int at(uint pos) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(UtilsPINVOKE.DataArrayi_at__SWIG_0(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setData(SWIGTYPE_p_int ptr, int size) {
    UtilsPINVOKE.DataArrayi_setData(swigCPtr, SWIGTYPE_p_int.getCPtr(ptr), size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getNumberOfComponents() {
    int ret = UtilsPINVOKE.DataArrayi_getNumberOfComponents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override AbstractDataArray cast(byte type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayi_cast(swigCPtr, type);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setValues(int[] val) {
    fixed ( int* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayi_setValues__SWIG_0(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void setValues(int[] val, int n) {
    fixed ( int* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayi_setValues__SWIG_1(swigCPtr, (global::System.IntPtr)swig_ptrTo_val, n);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void getValues(int[] val) {
    fixed ( int* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayi_getValues(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public static readonly int NumComponents = UtilsPINVOKE.DataArrayi_NumComponents_get();
}

}
