//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DataArrayuc : AbstractDataArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DataArrayuc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DataArrayuc_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DataArrayuc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DataArrayuc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DataArrayuc() : this(UtilsPINVOKE.new_DataArrayuc__SWIG_0(), true) {
  }

  public DataArrayuc(int size) : this(UtilsPINVOKE.new_DataArrayuc__SWIG_1(size), true) {
  }

  public DataArrayuc(DataArrayuc other) : this(UtilsPINVOKE.new_DataArrayuc__SWIG_2(DataArrayuc.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void resize(int size) {
    UtilsPINVOKE.DataArrayuc_resize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void fill(byte val) {
    UtilsPINVOKE.DataArrayuc_fill(swigCPtr, val);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void squeeze() {
    UtilsPINVOKE.DataArrayuc_squeeze(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(byte val) {
    UtilsPINVOKE.DataArrayuc_push_back__SWIG_0(swigCPtr, val);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(SWIGTYPE_p_unsigned_char val) {
    UtilsPINVOKE.DataArrayuc_push_back__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned_char.swigRelease(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator begin() {
    SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator ret = new SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator(UtilsPINVOKE.DataArrayuc_begin(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator end() {
    SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator ret = new SWIGTYPE_p_imstk__DataArrayT_unsigned_char_t__const_iterator(UtilsPINVOKE.DataArrayuc_end(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void reserve(int capacity) {
    UtilsPINVOKE.DataArrayuc_reserve(swigCPtr, capacity);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_unsigned_char getPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayuc_getPointer(swigCPtr);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override SWIGTYPE_p_void getVoidPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayuc_getVoidPointer(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned_char setValue(uint pos) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(UtilsPINVOKE.DataArrayuc_setValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte getValue(uint pos) {
    byte ret = UtilsPINVOKE.DataArrayuc_getValue(swigCPtr, pos);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_unsigned_char at(uint pos) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(UtilsPINVOKE.DataArrayuc_at__SWIG_0(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setData(SWIGTYPE_p_unsigned_char ptr, int size) {
    UtilsPINVOKE.DataArrayuc_setData(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(ptr), size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getNumberOfComponents() {
    int ret = UtilsPINVOKE.DataArrayuc_getNumberOfComponents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override AbstractDataArray cast(byte type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.DataArrayuc_cast(swigCPtr, type);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setValues(byte[] val) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayuc_setValues__SWIG_0(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void setValues(byte[] val, int n) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayuc_setValues__SWIG_1(swigCPtr, (global::System.IntPtr)swig_ptrTo_val, n);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void getValues(byte[] val) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.DataArrayuc_getValues(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public static readonly int NumComponents = UtilsPINVOKE.DataArrayuc_NumComponents_get();
}

}
