//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DeviceClient : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DeviceClient(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DeviceClient_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DeviceClient obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DeviceClient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static string buttonStateChanged() {
    string ret = UtilsPINVOKE.DeviceClient_buttonStateChanged();
    return ret;
  }

  public string getIp() {
    string ret = UtilsPINVOKE.DeviceClient_getIp(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setIp(string ip) {
    UtilsPINVOKE.DeviceClient_setIp(swigCPtr, ip);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getDeviceName() {
    string ret = UtilsPINVOKE.DeviceClient_getDeviceName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDeviceName(string deviceName) {
    UtilsPINVOKE.DeviceClient_setDeviceName(swigCPtr, deviceName);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getTrackingEnabled() {
    bool ret = UtilsPINVOKE.DeviceClient_getTrackingEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTrackingEnabled(bool status) {
    UtilsPINVOKE.DeviceClient_setTrackingEnabled(swigCPtr, status);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getAnalogicEnabled() {
    bool ret = UtilsPINVOKE.DeviceClient_getAnalogicEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setAnalogicEnabled(bool status) {
    UtilsPINVOKE.DeviceClient_setAnalogicEnabled(swigCPtr, status);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getButtonsEnabled() {
    bool ret = UtilsPINVOKE.DeviceClient_getButtonsEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setButtonsEnabled(bool status) {
    UtilsPINVOKE.DeviceClient_setButtonsEnabled(swigCPtr, status);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getForceEnabled() {
    bool ret = UtilsPINVOKE.DeviceClient_getForceEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setForceEnabled(bool status) {
    UtilsPINVOKE.DeviceClient_setForceEnabled(swigCPtr, status);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getPosition() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.DeviceClient_getPosition(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getVelocity() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.DeviceClient_getVelocity(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getAngularVelocity() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.DeviceClient_getAngularVelocity(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__QuaternionT_double_t getOrientation() {
    SWIGTYPE_p_Eigen__QuaternionT_double_t ret = new SWIGTYPE_p_Eigen__QuaternionT_double_t(UtilsPINVOKE.DeviceClient_getOrientation(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getOffset() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.DeviceClient_getOffset(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getForce() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.DeviceClient_getForce(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setForce(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t force) {
    UtilsPINVOKE.DeviceClient_setForce(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(force));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public UnorderedMapIntInt getButtons() {
    UnorderedMapIntInt ret = new UnorderedMapIntInt(UtilsPINVOKE.DeviceClient_getButtons(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getButton(int buttonId) {
    int ret = UtilsPINVOKE.DeviceClient_getButton(swigCPtr, buttonId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorDouble getAnalog() {
    VectorDouble ret = new VectorDouble(UtilsPINVOKE.DeviceClient_getAnalog__SWIG_0(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getAnalog(int i) {
    double ret = UtilsPINVOKE.DeviceClient_getAnalog__SWIG_1(swigCPtr, i);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void update() {
    UtilsPINVOKE.DeviceClient_update(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
