//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DummyClient : DeviceClient {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DummyClient(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DummyClient_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DummyClient obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DummyClient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public DummyClient(string name) : this(UtilsPINVOKE.new_DummyClient__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public DummyClient() : this(UtilsPINVOKE.new_DummyClient__SWIG_1(), true) {
  }

  public void setPosition(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    UtilsPINVOKE.DummyClient_setPosition(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setVelocity(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t vel) {
    UtilsPINVOKE.DummyClient_setVelocity(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(vel));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setOrientation(SWIGTYPE_p_Eigen__QuaternionT_double_t orient) {
    UtilsPINVOKE.DummyClient_setOrientation__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orient));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setOrientation(SWIGTYPE_p_double transform) {
    UtilsPINVOKE.DummyClient_setOrientation__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(transform));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setButton(uint buttonId, bool buttonStatus) {
    UtilsPINVOKE.DummyClient_setButton(swigCPtr, buttonId, buttonStatus);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
