//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DynamicalModelRigidBodyState2 : AbstractDynamicalModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DynamicalModelRigidBodyState2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DynamicalModelRigidBodyState2_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DynamicalModelRigidBodyState2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DynamicalModelRigidBodyState2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RigidBodyState2 getInitialState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelRigidBodyState2_getInitialState(swigCPtr);
    RigidBodyState2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new RigidBodyState2(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RigidBodyState2 getCurrentState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelRigidBodyState2_getCurrentState(swigCPtr);
    RigidBodyState2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new RigidBodyState2(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RigidBodyState2 getPreviousState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelRigidBodyState2_getPreviousState(swigCPtr);
    RigidBodyState2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new RigidBodyState2(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void resetToInitialState() {
    UtilsPINVOKE.DynamicalModelRigidBodyState2_resetToInitialState(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
