//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DynamicalModelSphState : AbstractDynamicalModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DynamicalModelSphState(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DynamicalModelSphState_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DynamicalModelSphState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DynamicalModelSphState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SphState getInitialState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelSphState_getInitialState(swigCPtr);
    SphState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphState(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SphState getCurrentState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelSphState_getCurrentState(swigCPtr);
    SphState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphState(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SphState getPreviousState() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicalModelSphState_getPreviousState(swigCPtr);
    SphState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SphState(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void resetToInitialState() {
    UtilsPINVOKE.DynamicalModelSphState_resetToInitialState(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
