//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class DynamicObject : CollidingObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DynamicObject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.DynamicObject_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DynamicObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_DynamicObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Geometry getPhysicsGeometry() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicObject_getPhysicsGeometry(swigCPtr);
    Geometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new Geometry(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setPhysicsGeometry(Geometry geometry) {
    UtilsPINVOKE.DynamicObject_setPhysicsGeometry(swigCPtr, Geometry.getCPtr(geometry));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public GeometryMap getPhysicsToCollidingMap() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicObject_getPhysicsToCollidingMap(swigCPtr);
    GeometryMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new GeometryMap(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPhysicsToCollidingMap(GeometryMap map) {
    UtilsPINVOKE.DynamicObject_setPhysicsToCollidingMap(swigCPtr, GeometryMap.getCPtr(map));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public GeometryMap getPhysicsToVisualMap() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicObject_getPhysicsToVisualMap(swigCPtr);
    GeometryMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new GeometryMap(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPhysicsToVisualMap(GeometryMap map) {
    UtilsPINVOKE.DynamicObject_setPhysicsToVisualMap(swigCPtr, GeometryMap.getCPtr(map));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual AbstractDynamicalModel getDynamicalModel() {
    global::System.IntPtr cPtr = UtilsPINVOKE.DynamicObject_getDynamicalModel(swigCPtr);
    AbstractDynamicalModel ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDynamicalModel(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setDynamicalModel(AbstractDynamicalModel dynaModel) {
    UtilsPINVOKE.DynamicObject_setDynamicalModel(swigCPtr, AbstractDynamicalModel.getCPtr(dynaModel));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getNumOfDOF() {
    uint ret = UtilsPINVOKE.DynamicObject_getNumOfDOF(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updateGeometries() {
    UtilsPINVOKE.DynamicObject_updateGeometries(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updatePhysicsGeometry() {
    UtilsPINVOKE.DynamicObject_updatePhysicsGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool initialize() {
    bool ret = UtilsPINVOKE.DynamicObject_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void reset() {
    UtilsPINVOKE.DynamicObject_reset(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
