//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class FemModelConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal FemModelConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FemModelConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FemModelConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_FemModelConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public FeMethodType m_femMethod {
    set {
      UtilsPINVOKE.FemModelConfig_m_femMethod_set(swigCPtr, (int)value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      FeMethodType ret = (FeMethodType)UtilsPINVOKE.FemModelConfig_m_femMethod_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public HyperElasticMaterialType m_hyperElasticMaterialType {
    set {
      UtilsPINVOKE.FemModelConfig_m_hyperElasticMaterialType_set(swigCPtr, (int)value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      HyperElasticMaterialType ret = (HyperElasticMaterialType)UtilsPINVOKE.FemModelConfig_m_hyperElasticMaterialType_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string m_fixedDOFFilename {
    set {
      UtilsPINVOKE.FemModelConfig_m_fixedDOFFilename_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = UtilsPINVOKE.FemModelConfig_m_fixedDOFFilename_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VectorSizet m_fixedNodeIds {
    set {
      UtilsPINVOKE.FemModelConfig_m_fixedNodeIds_set(swigCPtr, VectorSizet.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.FemModelConfig_m_fixedNodeIds_get(swigCPtr);
      VectorSizet ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorSizet(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_dampingMassCoefficient {
    set {
      UtilsPINVOKE.FemModelConfig_m_dampingMassCoefficient_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_dampingMassCoefficient_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_dampingStiffnessCoefficient {
    set {
      UtilsPINVOKE.FemModelConfig_m_dampingStiffnessCoefficient_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_dampingStiffnessCoefficient_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_dampingLaplacianCoefficient {
    set {
      UtilsPINVOKE.FemModelConfig_m_dampingLaplacianCoefficient_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_dampingLaplacianCoefficient_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_deformationCompliance {
    set {
      UtilsPINVOKE.FemModelConfig_m_deformationCompliance_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_deformationCompliance_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_compressionResistance {
    set {
      UtilsPINVOKE.FemModelConfig_m_compressionResistance_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_compressionResistance_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_inversionThreshold {
    set {
      UtilsPINVOKE.FemModelConfig_m_inversionThreshold_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_inversionThreshold_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_gravity {
    set {
      UtilsPINVOKE.FemModelConfig_m_gravity_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.FemModelConfig_m_gravity_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public FemModelConfig() : this(UtilsPINVOKE.new_FemModelConfig(), true) {
  }

}

}
