//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Geometry : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Geometry(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Geometry_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Geometry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Geometry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual string getTypeName() {
    string ret = UtilsPINVOKE.Geometry_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string modified() {
    string ret = UtilsPINVOKE.Geometry_modified();
    return ret;
  }

  public virtual void print() {
    UtilsPINVOKE.Geometry_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual double getVolume() {
    double ret = UtilsPINVOKE.Geometry_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner, double paddingPercent) {
    UtilsPINVOKE.Geometry_computeBoundingBox__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner) {
    UtilsPINVOKE.Geometry_computeBoundingBox__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getCenter() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Geometry_getCenter(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void translate(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t t, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_translate__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(t), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void translate(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t t) {
    UtilsPINVOKE.Geometry_translate__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(t));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void translate(double x, double y, double z, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_translate__SWIG_2(swigCPtr, x, y, z, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void translate(double x, double y, double z) {
    UtilsPINVOKE.Geometry_translate__SWIG_3(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__QuaternionT_double_t q, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_rotate__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(q), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__QuaternionT_double_t q) {
    UtilsPINVOKE.Geometry_rotate__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(q));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__MatrixT_double_3_3_t m, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_rotate__SWIG_2(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(m), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__MatrixT_double_3_3_t m) {
    UtilsPINVOKE.Geometry_rotate__SWIG_3(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(m));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t axis, double radians, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_rotate__SWIG_4(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(axis), radians, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void rotate(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t axis, double radians) {
    UtilsPINVOKE.Geometry_rotate__SWIG_5(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(axis), radians);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void scale(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t scaling, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_scale__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(scaling), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void scale(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t scaling) {
    UtilsPINVOKE.Geometry_scale__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(scaling));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void scale(double scaling, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_scale__SWIG_2(swigCPtr, scaling, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void scale(double scaling) {
    UtilsPINVOKE.Geometry_scale__SWIG_3(swigCPtr, scaling);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void transform(SWIGTYPE_p_Eigen__MatrixT_double_4_4_t T, Geometry.TransformType type) {
    UtilsPINVOKE.Geometry_transform__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(T), (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void transform(SWIGTYPE_p_Eigen__MatrixT_double_4_4_t T) {
    UtilsPINVOKE.Geometry_transform__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(T));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getTranslation() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Geometry_getTranslation(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTranslation(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t t) {
    UtilsPINVOKE.Geometry_setTranslation__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(t));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setTranslation(double x, double y, double z) {
    UtilsPINVOKE.Geometry_setTranslation__SWIG_1(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_3_t getRotation() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_3_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_3_t(UtilsPINVOKE.Geometry_getRotation(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRotation(SWIGTYPE_p_Eigen__MatrixT_double_3_3_t m) {
    UtilsPINVOKE.Geometry_setRotation__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(m));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRotation(SWIGTYPE_p_Eigen__QuaternionT_double_t q) {
    UtilsPINVOKE.Geometry_setRotation__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(q));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setRotation(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t axis, double angle) {
    UtilsPINVOKE.Geometry_setRotation__SWIG_2(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(axis), angle);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getScaling() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Geometry_getScaling(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setScaling(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t s) {
    UtilsPINVOKE.Geometry_setScaling__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(s));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setScaling(double s) {
    UtilsPINVOKE.Geometry_setScaling__SWIG_1(swigCPtr, s);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_4_4_t getTransform() {
    SWIGTYPE_p_Eigen__MatrixT_double_4_4_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_4_4_t(UtilsPINVOKE.Geometry_getTransform(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTransform(SWIGTYPE_p_Eigen__MatrixT_double_4_4_t m) {
    UtilsPINVOKE.Geometry_setTransform(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_4_4_t.getCPtr(m));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getName() {
    string ret = UtilsPINVOKE.Geometry_getName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setName(string name) {
    UtilsPINVOKE.Geometry_setName(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint getGlobalId() {
    uint ret = UtilsPINVOKE.Geometry_getGlobalId(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint getNumGlobalIds() {
    uint ret = UtilsPINVOKE.Geometry_getNumGlobalIds();
    return ret;
  }

  public virtual bool isMesh() {
    bool ret = UtilsPINVOKE.Geometry_isMesh(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void postModified() {
    UtilsPINVOKE.Geometry_postModified(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updatePostTransformData() {
    UtilsPINVOKE.Geometry_updatePostTransformData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public enum TransformType {
    ApplyToData,
    ConcatenateToTransform
  }

  public enum DataType {
    PreTransform,
    PostTransform
  }

}

}
