//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class ImageData : PointSet {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ImageData(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.ImageData_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_ImageData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ImageData() : this(UtilsPINVOKE.new_ImageData(), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.ImageData_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.ImageData_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void print() {
    UtilsPINVOKE.ImageData_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getVolume() {
    double ret = UtilsPINVOKE.ImageData_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_int_3_1_t getDimensions() {
    SWIGTYPE_p_Eigen__MatrixT_int_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_int_3_1_t(UtilsPINVOKE.ImageData_getDimensions(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getNumComponents() {
    int ret = UtilsPINVOKE.ImageData_getNumComponents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_void getVoidPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.ImageData_getVoidPointer(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getScalarIndex(int x, int y, int z) {
    uint ret = UtilsPINVOKE.ImageData_getScalarIndex__SWIG_0(swigCPtr, x, y, z);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getScalarIndex(int x, int y) {
    uint ret = UtilsPINVOKE.ImageData_getScalarIndex__SWIG_1(swigCPtr, x, y);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getScalarIndex(SWIGTYPE_p_Eigen__MatrixT_int_3_1_t imgCoord) {
    uint ret = UtilsPINVOKE.ImageData_getScalarIndex__SWIG_2(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(imgCoord));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint getScalarIndex(int x, int y, int z, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t dims, int numComps) {
    uint ret = UtilsPINVOKE.ImageData_getScalarIndex__SWIG_3(x, y, z, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(dims), numComps);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImageData cast(byte type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.ImageData_cast(swigCPtr, type);
    ImageData ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImageData(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getInvSpacing() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.ImageData_getInvSpacing(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte getScalarType() {
    byte ret = UtilsPINVOKE.ImageData_getScalarType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_6_1_t getBounds() {
    SWIGTYPE_p_Eigen__MatrixT_double_6_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_6_1_t(UtilsPINVOKE.ImageData_getBounds(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner, double arg2) {
    UtilsPINVOKE.ImageData_computeBoundingBox(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner), arg2);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public AbstractDataArray getScalars() {
    global::System.IntPtr cPtr = UtilsPINVOKE.ImageData_getScalars(swigCPtr);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setScalars(AbstractDataArray scalars, int numComps, SWIGTYPE_p_int dim) {
    UtilsPINVOKE.ImageData_setScalars(swigCPtr, AbstractDataArray.getCPtr(scalars), numComps, SWIGTYPE_p_int.getCPtr(dim));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getOrigin() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.ImageData_getOrigin(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOrigin(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t origin) {
    UtilsPINVOKE.ImageData_setOrigin(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(origin));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getSpacing() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.ImageData_getSpacing(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSpacing(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t spacing) {
    UtilsPINVOKE.ImageData_setSpacing(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(spacing));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void allocate(byte type, int numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t dims, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t spacing, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t origin) {
    UtilsPINVOKE.ImageData_allocate__SWIG_0(swigCPtr, type, numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(dims), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(spacing), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(origin));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void allocate(byte type, int numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t dims, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t spacing) {
    UtilsPINVOKE.ImageData_allocate__SWIG_1(swigCPtr, type, numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(dims), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(spacing));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void allocate(byte type, int numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t dims) {
    UtilsPINVOKE.ImageData_allocate__SWIG_2(swigCPtr, type, numComps, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(dims));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computePoints() {
    UtilsPINVOKE.ImageData_computePoints(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void clear() {
    UtilsPINVOKE.ImageData_clear(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
