//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class KeyboardSceneControl : KeyboardControl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal KeyboardSceneControl(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.KeyboardSceneControl_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KeyboardSceneControl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_KeyboardSceneControl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public KeyboardSceneControl(string name) : this(UtilsPINVOKE.new_KeyboardSceneControl__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public KeyboardSceneControl() : this(UtilsPINVOKE.new_KeyboardSceneControl__SWIG_1(), true) {
  }

  public void setModuleDriver(ModuleDriverWeakPtr driver) {
    UtilsPINVOKE.KeyboardSceneControl_setModuleDriver(swigCPtr, ModuleDriverWeakPtr.getCPtr(driver));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSceneManager(SceneManagerWeakPtr sceneManager) {
    UtilsPINVOKE.KeyboardSceneControl_setSceneManager(swigCPtr, SceneManagerWeakPtr.getCPtr(sceneManager));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSceneControlText(SWIGTYPE_p_std__shared_ptrT_imstk__SceneControlText_t sceneControlText) {
    UtilsPINVOKE.KeyboardSceneControl_setSceneControlText(swigCPtr, SWIGTYPE_p_std__shared_ptrT_imstk__SceneControlText_t.getCPtr(sceneControlText));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void printControls() {
    UtilsPINVOKE.KeyboardSceneControl_printControls(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void OnKeyPress(char key) {
    UtilsPINVOKE.KeyboardSceneControl_OnKeyPress(swigCPtr, key);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
