//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class LineMesh : CellMesh2 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal LineMesh(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.LineMesh_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LineMesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_LineMesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public LineMesh() : this(UtilsPINVOKE.new_LineMesh(), true) {
  }

  public int getNumLines() {
    int ret = UtilsPINVOKE.LineMesh_getNumLines(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLinesIndices(VecDataArray2i indices) {
    UtilsPINVOKE.LineMesh_setLinesIndices(swigCPtr, VecDataArray2i.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecDataArray2i getLinesIndices() {
    global::System.IntPtr cPtr = UtilsPINVOKE.LineMesh_getLinesIndices(swigCPtr);
    VecDataArray2i ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecDataArray2i(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.LineMesh_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.LineMesh_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
