//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class MeshIO : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MeshIO(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MeshIO obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MeshIO obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MeshIO() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_MeshIO(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MeshIO() : this(UtilsPINVOKE.new_MeshIO(), true) {
  }

  public static PointSet read(string filePath) {
    global::System.IntPtr cPtr = UtilsPINVOKE.MeshIO_read(filePath);
    PointSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointSet(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool write(PointSet imstkMesh, string filePath) {
    bool ret = UtilsPINVOKE.MeshIO_write(PointSet.getCPtr(imstkMesh), filePath);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool fileExists(string file, SWIGTYPE_p_bool isDirectory) {
    bool ret = UtilsPINVOKE.MeshIO_fileExists(file, SWIGTYPE_p_bool.getCPtr(isDirectory));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MeshFileType getFileType(string filePath) {
    MeshFileType ret = (MeshFileType)UtilsPINVOKE.MeshIO_getFileType(filePath);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static ImageData readImageData(string filePath) {
    global::System.IntPtr cPtr = UtilsPINVOKE.MeshIO_readImageData(filePath);
    ImageData ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImageData(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PointSet readPointSet(string filePath) {
    global::System.IntPtr cPtr = UtilsPINVOKE.MeshIO_readPointSet(filePath);
    PointSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointSet(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SurfaceMesh readSurfaceMesh(string filePath) {
    global::System.IntPtr cPtr = UtilsPINVOKE.MeshIO_readSurfaceMesh(filePath);
    SurfaceMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new SurfaceMesh(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TetrahedralMesh readTetrahedralMesh(string filePath) {
    global::System.IntPtr cPtr = UtilsPINVOKE.MeshIO_readTetrahedralMesh(filePath);
    TetrahedralMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new TetrahedralMesh(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
