//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Module : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Module(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Module_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Module obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Module(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual string getTypeName() {
    string ret = UtilsPINVOKE.Module_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string preUpdate() {
    string ret = UtilsPINVOKE.Module_preUpdate();
    return ret;
  }

  public static string postUpdate() {
    string ret = UtilsPINVOKE.Module_postUpdate();
    return ret;
  }

  public static string end() {
    string ret = UtilsPINVOKE.Module_end();
    return ret;
  }

  public double getDt() {
    double ret = UtilsPINVOKE.Module_getDt(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDt(double dt) {
    UtilsPINVOKE.Module_setDt(swigCPtr, dt);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getInit() {
    bool ret = UtilsPINVOKE.Module_getInit(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getPaused() {
    bool ret = UtilsPINVOKE.Module_getPaused(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPaused(bool paused) {
    UtilsPINVOKE.Module_setPaused(swigCPtr, paused);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMuteUpdateEvents(bool mute) {
    UtilsPINVOKE.Module_setMuteUpdateEvents(swigCPtr, mute);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getMuteUpdateEvents() {
    bool ret = UtilsPINVOKE.Module_getMuteUpdateEvents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Module.ExecutionType getExecutionType() {
    Module.ExecutionType ret = (Module.ExecutionType)UtilsPINVOKE.Module_getExecutionType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setExecutionType(Module.ExecutionType type) {
    UtilsPINVOKE.Module_setExecutionType(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setSleepDelay(double ms) {
    UtilsPINVOKE.Module_setSleepDelay(swigCPtr, ms);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSleepDelay() {
    double ret = UtilsPINVOKE.Module_getSleepDelay(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void pause() {
    UtilsPINVOKE.Module_pause(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void resume() {
    UtilsPINVOKE.Module_resume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void init() {
    UtilsPINVOKE.Module_init(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void update() {
    UtilsPINVOKE.Module_update(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void uninit() {
    UtilsPINVOKE.Module_uninit(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool initModule() {
    bool ret = UtilsPINVOKE.Module_initModule(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void updateModule() {
    UtilsPINVOKE.Module_updateModule(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void uninitModule() {
    UtilsPINVOKE.Module_uninitModule(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public enum ExecutionType {
    SEQUENTIAL,
    PARALLEL,
    ADAPTIVE
  }

}

}
