//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class MouseControl : DeviceControl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal MouseControl(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.MouseControl_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MouseControl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_MouseControl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public MouseControl(string name) : this(UtilsPINVOKE.new_MouseControl__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public MouseControl() : this(UtilsPINVOKE.new_MouseControl__SWIG_1(), true) {
  }

  public override void setDevice(DeviceClient device) {
    UtilsPINVOKE.MouseControl_setDevice(swigCPtr, DeviceClient.getCPtr(device));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void OnButtonPress(int arg0) {
    UtilsPINVOKE.MouseControl_OnButtonPress(swigCPtr, arg0);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void OnButtonRelease(int arg0) {
    UtilsPINVOKE.MouseControl_OnButtonRelease(swigCPtr, arg0);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void OnScroll(double arg0) {
    UtilsPINVOKE.MouseControl_OnScroll(swigCPtr, arg0);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void OnMouseMove(SWIGTYPE_p_Eigen__MatrixT_double_2_1_t arg0) {
    UtilsPINVOKE.MouseControl_OnMouseMove(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(arg0));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
