//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class MouseDeviceClient : DeviceClient {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal MouseDeviceClient(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.MouseDeviceClient_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MouseDeviceClient obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_MouseDeviceClient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static string mouseButtonPress() {
    string ret = UtilsPINVOKE.MouseDeviceClient_mouseButtonPress();
    return ret;
  }

  public static string mouseButtonRelease() {
    string ret = UtilsPINVOKE.MouseDeviceClient_mouseButtonRelease();
    return ret;
  }

  public static string mouseScroll() {
    string ret = UtilsPINVOKE.MouseDeviceClient_mouseScroll();
    return ret;
  }

  public static string mouseMove() {
    string ret = UtilsPINVOKE.MouseDeviceClient_mouseMove();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t getPos() {
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(UtilsPINVOKE.MouseDeviceClient_getPos(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t getPrevPos() {
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(UtilsPINVOKE.MouseDeviceClient_getPrevPos(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isButtonDown(int buttonId) {
    bool ret = UtilsPINVOKE.MouseDeviceClient_isButtonDown(swigCPtr, buttonId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
