//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class NeedlePbdCH : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal NeedlePbdCH(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NeedlePbdCH obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NeedlePbdCH() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_NeedlePbdCH(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public NeedlePbdCH() : this(UtilsPINVOKE.new_NeedlePbdCH(), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.NeedlePbdCH_getStaticTypeName();
    return ret;
  }

  public string getTypeName() {
    string ret = UtilsPINVOKE.NeedlePbdCH_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public class PuncturePoint : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal PuncturePoint(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PuncturePoint obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PuncturePoint obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~PuncturePoint() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            UtilsPINVOKE.delete_NeedlePbdCH_PuncturePoint(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public int triId {
      set {
        UtilsPINVOKE.NeedlePbdCH_PuncturePoint_triId_set(swigCPtr, value);
      } 
      get {
        int ret = UtilsPINVOKE.NeedlePbdCH_PuncturePoint_triId_get(swigCPtr);
        return ret;
      } 
    }
  
    public SWIGTYPE_p_Eigen__MatrixT_int_3_1_t triVertIds {
      set {
        UtilsPINVOKE.NeedlePbdCH_PuncturePoint_triVertIds_set(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(value));
        if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        SWIGTYPE_p_Eigen__MatrixT_int_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_int_3_1_t(UtilsPINVOKE.NeedlePbdCH_PuncturePoint_triVertIds_get(swigCPtr), true);
        if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t baryCoords {
      set {
        UtilsPINVOKE.NeedlePbdCH_PuncturePoint_baryCoords_set(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(value));
        if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      } 
      get {
        SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.NeedlePbdCH_PuncturePoint_baryCoords_get(swigCPtr), true);
        if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
        return ret;
      } 
    }
  
    public int segId {
      set {
        UtilsPINVOKE.NeedlePbdCH_PuncturePoint_segId_set(swigCPtr, value);
      } 
      get {
        int ret = UtilsPINVOKE.NeedlePbdCH_PuncturePoint_segId_get(swigCPtr);
        return ret;
      } 
    }
  
    public PuncturePoint() : this(UtilsPINVOKE.new_NeedlePbdCH_PuncturePoint(), true) {
    }
  
  }

  public class PunctureData : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal PunctureData(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PunctureData obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PunctureData obj) {
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
        global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.Dispose();
        return ptr;
      } else {
        return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  
    ~PunctureData() {
      Dispose(false);
    }
  
    public void Dispose() {
      Dispose(true);
      global::System.GC.SuppressFinalize(this);
    }
  
    protected virtual void Dispose(bool disposing) {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            UtilsPINVOKE.delete_NeedlePbdCH_PunctureData(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
      }
    }
  
    public VectorPuncturePoint thread {
      set {
        UtilsPINVOKE.NeedlePbdCH_PunctureData_thread_set(swigCPtr, VectorPuncturePoint.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = UtilsPINVOKE.NeedlePbdCH_PunctureData_thread_get(swigCPtr);
        VectorPuncturePoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorPuncturePoint(cPtr, false);
        return ret;
      } 
    }
  
    public VectorPuncturePoint needle {
      set {
        UtilsPINVOKE.NeedlePbdCH_PunctureData_needle_set(swigCPtr, VectorPuncturePoint.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = UtilsPINVOKE.NeedlePbdCH_PunctureData_needle_get(swigCPtr);
        VectorPuncturePoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorPuncturePoint(cPtr, false);
        return ret;
      } 
    }
  
    public VectorVectorPuncturePoint stitch {
      set {
        UtilsPINVOKE.NeedlePbdCH_PunctureData_stitch_set(swigCPtr, VectorVectorPuncturePoint.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = UtilsPINVOKE.NeedlePbdCH_PunctureData_stitch_get(swigCPtr);
        VectorVectorPuncturePoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorPuncturePoint(cPtr, false);
        return ret;
      } 
    }
  
    public PunctureData() : this(UtilsPINVOKE.new_NeedlePbdCH_PunctureData(), true) {
    }
  
  }

  public void init(PbdObject threadObj) {
    UtilsPINVOKE.NeedlePbdCH_init(swigCPtr, PbdObject.getCPtr(threadObj));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void stitch() {
    UtilsPINVOKE.NeedlePbdCH_stitch(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void handle(VectorCollisionElement elementsA, VectorCollisionElement elementsB) {
    UtilsPINVOKE.NeedlePbdCH_handle(swigCPtr, VectorCollisionElement.getCPtr(elementsA), VectorCollisionElement.getCPtr(elementsB));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void generateNewPunctureData() {
    UtilsPINVOKE.NeedlePbdCH_generateNewPunctureData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addPunctureConstraints() {
    UtilsPINVOKE.NeedlePbdCH_addPunctureConstraints(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setNeedleToSurfaceStiffness(double stiffness) {
    UtilsPINVOKE.NeedlePbdCH_setNeedleToSurfaceStiffness(swigCPtr, stiffness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getNeedleToSurfaceStiffness() {
    double ret = UtilsPINVOKE.NeedlePbdCH_getNeedleToSurfaceStiffness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSurfaceToNeedleStiffness(double stiffness) {
    UtilsPINVOKE.NeedlePbdCH_setSurfaceToNeedleStiffness(swigCPtr, stiffness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSurfaceToNeedleStiffness() {
    double ret = UtilsPINVOKE.NeedlePbdCH_getSurfaceToNeedleStiffness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setThreadToSurfaceStiffness(double stiffness) {
    UtilsPINVOKE.NeedlePbdCH_setThreadToSurfaceStiffness(swigCPtr, stiffness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getThreadToSurfaceStiffness() {
    double ret = UtilsPINVOKE.NeedlePbdCH_getThreadToSurfaceStiffness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSurfaceToThreadStiffness(double stiffness) {
    UtilsPINVOKE.NeedlePbdCH_setSurfaceToThreadStiffness(swigCPtr, stiffness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSurfaceToThreadStiffness() {
    double ret = UtilsPINVOKE.NeedlePbdCH_getSurfaceToThreadStiffness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPunctureDotThreshold(double threshold) {
    UtilsPINVOKE.NeedlePbdCH_setPunctureDotThreshold(swigCPtr, threshold);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getPunctureDotThreshold() {
    double ret = UtilsPINVOKE.NeedlePbdCH_getPunctureDotThreshold(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public NeedlePbdCH.PunctureData getPunctureData() {
    NeedlePbdCH.PunctureData ret = new NeedlePbdCH.PunctureData(UtilsPINVOKE.NeedlePbdCH_getPunctureData(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
