//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class NeedleInteraction : PbdObjectCollision {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal NeedleInteraction(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.NeedleInteraction_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NeedleInteraction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_NeedleInteraction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public NeedleInteraction(PbdObject tissueObj, PbdObject needleObj, PbdObject threadObj) : this(UtilsPINVOKE.new_NeedleInteraction(PbdObject.getCPtr(tissueObj), PbdObject.getCPtr(needleObj), PbdObject.getCPtr(threadObj)), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.NeedleInteraction_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.NeedleInteraction_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void stitch() {
    UtilsPINVOKE.NeedleInteraction_stitch(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public NeedlePbdCH.PunctureData getPunctureData() {
    NeedlePbdCH.PunctureData ret = new NeedlePbdCH.PunctureData(UtilsPINVOKE.NeedleInteraction_getPunctureData(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
