//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PbdModel : AbstractDynamicalModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PbdModel(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.PbdModel_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PbdModel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_PbdModel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PbdModel() : this(UtilsPINVOKE.new_PbdModel(), true) {
  }

  public override void resetToInitialState() {
    UtilsPINVOKE.PbdModel_resetToInitialState(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void configure(PbdModelConfig params_) {
    UtilsPINVOKE.PbdModel_configure(swigCPtr, PbdModelConfig.getCPtr(params_));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public PbdBody addBody() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdModel_addBody(swigCPtr);
    PbdBody ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdBody(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void removeBody(PbdBody body) {
    UtilsPINVOKE.PbdModel_removeBody(swigCPtr, PbdBody.getCPtr(body));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public PbdBody getBody(uint index) {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdModel_getBody(swigCPtr, index);
    PbdBody ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdBody(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PbdState getBodies() {
    PbdState ret = new PbdState(UtilsPINVOKE.PbdModel_getBodies(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, SWIGTYPE_p_Eigen__QuaternionT_double_t orientation, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t inertia, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t velocity, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t angularVelocity, bool persist) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orientation), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(inertia), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(velocity), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(angularVelocity), persist), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, SWIGTYPE_p_Eigen__QuaternionT_double_t orientation, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t inertia, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t velocity, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t angularVelocity) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orientation), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(inertia), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(velocity), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(angularVelocity)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, SWIGTYPE_p_Eigen__QuaternionT_double_t orientation, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t inertia, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t velocity) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_2(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orientation), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(inertia), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(velocity)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, SWIGTYPE_p_Eigen__QuaternionT_double_t orientation, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t inertia) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_3(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), SWIGTYPE_p_Eigen__QuaternionT_double_t.getCPtr(orientation), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_3_t.getCPtr(inertia)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t velocity, bool persist) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_4(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(velocity), persist), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double mass, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t velocity) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_5(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), mass, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(velocity)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntPair addVirtualParticle(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double mass) {
    IntPair ret = new IntPair(UtilsPINVOKE.PbdModel_addVirtualParticle__SWIG_6(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), mass), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clearVirtualParticles() {
    UtilsPINVOKE.PbdModel_clearVirtualParticles(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public PbdModelConfig getConfig() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdModel_getConfig(swigCPtr);
    PbdModelConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdModelConfig(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addConstraints(SWIGTYPE_p_std__shared_ptrT_std__unordered_setT_size_t_t_t vertices, int bodyId) {
    UtilsPINVOKE.PbdModel_addConstraints(swigCPtr, SWIGTYPE_p_std__shared_ptrT_std__unordered_setT_size_t_t_t.getCPtr(vertices), bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setTimeStep(double timeStep) {
    UtilsPINVOKE.PbdModel_setTimeStep(swigCPtr, timeStep);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getTimeStep() {
    double ret = UtilsPINVOKE.PbdModel_getTimeStep(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setVelocityThreshold(double velCap) {
    UtilsPINVOKE.PbdModel_setVelocityThreshold(swigCPtr, velCap);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getVelocityThreshold() {
    double ret = UtilsPINVOKE.PbdModel_getVelocityThreshold(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PbdConstraintContainer getConstraints() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdModel_getConstraints(swigCPtr);
    PbdConstraintContainer ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdConstraintContainer(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void integratePosition() {
    UtilsPINVOKE.PbdModel_integratePosition__SWIG_0(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void integratePosition(PbdBody body) {
    UtilsPINVOKE.PbdModel_integratePosition__SWIG_1(swigCPtr, PbdBody.getCPtr(body));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateVelocity() {
    UtilsPINVOKE.PbdModel_updateVelocity__SWIG_0(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void updateVelocity(PbdBody body) {
    UtilsPINVOKE.PbdModel_updateVelocity__SWIG_1(swigCPtr, PbdBody.getCPtr(body));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void solveConstraints() {
    UtilsPINVOKE.PbdModel_solveConstraints(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool initialize() {
    bool ret = UtilsPINVOKE.PbdModel_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setConstraintPartitionThreshold(uint threshold) {
    UtilsPINVOKE.PbdModel_setConstraintPartitionThreshold(swigCPtr, threshold);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_imstk__PbdSolver getSolver() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdModel_getSolver(swigCPtr);
    SWIGTYPE_p_imstk__PbdSolver ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_imstk__PbdSolver(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSolver(SWIGTYPE_p_imstk__PbdSolver solver) {
    UtilsPINVOKE.PbdModel_setSolver(swigCPtr, SWIGTYPE_p_imstk__PbdSolver.getCPtr(solver));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getIntegratePositionNode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.PbdModel_getIntegratePositionNode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getSolveNode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.PbdModel_getSolveNode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t getUpdateVelocityNode() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t(UtilsPINVOKE.PbdModel_getUpdateVelocityNode(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
