//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PbdModelConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal PbdModelConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PbdModelConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PbdModelConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_PbdModelConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void enableConstraint(PbdModelConfig.ConstraintGenType type, double stiffness, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableConstraint__SWIG_0(swigCPtr, (int)type, stiffness, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableConstraint(PbdModelConfig.ConstraintGenType type, double stiffness) {
    UtilsPINVOKE.PbdModelConfig_enableConstraint__SWIG_1(swigCPtr, (int)type, stiffness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableDistanceConstraint(double stiffness, double stretch, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableDistanceConstraint(swigCPtr, stiffness, stretch, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableBendConstraint(double stiffness, int stride, bool restLength0, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableBendConstraint__SWIG_0(swigCPtr, stiffness, stride, restLength0, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableBendConstraint(double stiffness, int stride, bool restLength0) {
    UtilsPINVOKE.PbdModelConfig_enableBendConstraint__SWIG_1(swigCPtr, stiffness, stride, restLength0);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableBendConstraint(double stiffness, int stride) {
    UtilsPINVOKE.PbdModelConfig_enableBendConstraint__SWIG_2(swigCPtr, stiffness, stride);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableConstantDensityConstraint(double stiffness, double particleRadius, double restDensity, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableConstantDensityConstraint__SWIG_0(swigCPtr, stiffness, particleRadius, restDensity, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableConstantDensityConstraint(double stiffness, double particleRadius, double restDensity) {
    UtilsPINVOKE.PbdModelConfig_enableConstantDensityConstraint__SWIG_1(swigCPtr, stiffness, particleRadius, restDensity);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableConstantDensityConstraint(double stiffness, double particleRadius) {
    UtilsPINVOKE.PbdModelConfig_enableConstantDensityConstraint__SWIG_2(swigCPtr, stiffness, particleRadius);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableFemConstraint(PbdFemConstraint.MaterialType material, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableFemConstraint__SWIG_0(swigCPtr, (int)material, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableFemConstraint(PbdFemConstraint.MaterialType material) {
    UtilsPINVOKE.PbdModelConfig_enableFemConstraint__SWIG_1(swigCPtr, (int)material);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void enableFemConstraint(PbdFemConstraint.MaterialType material, double youngsModulus, double poissonRatio, int bodyId) {
    UtilsPINVOKE.PbdModelConfig_enableFemConstraint__SWIG_2(swigCPtr, (int)material, youngsModulus, poissonRatio, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeElasticConstants() {
    UtilsPINVOKE.PbdModelConfig_computeElasticConstants(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBodyDamping(int bodyId, double linearDampCoeff, double angularDampCoeff) {
    UtilsPINVOKE.PbdModelConfig_setBodyDamping__SWIG_0(swigCPtr, bodyId, linearDampCoeff, angularDampCoeff);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBodyDamping(int bodyId, double linearDampCoeff) {
    UtilsPINVOKE.PbdModelConfig_setBodyDamping__SWIG_1(swigCPtr, bodyId, linearDampCoeff);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getLinearDamping(int bodyId) {
    double ret = UtilsPINVOKE.PbdModelConfig_getLinearDamping(swigCPtr, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getAngularDamping(int bodyId) {
    double ret = UtilsPINVOKE.PbdModelConfig_getAngularDamping(swigCPtr, bodyId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double m_linearDampingCoeff {
    set {
      UtilsPINVOKE.PbdModelConfig_m_linearDampingCoeff_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.PbdModelConfig_m_linearDampingCoeff_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_angularDampingCoeff {
    set {
      UtilsPINVOKE.PbdModelConfig_m_angularDampingCoeff_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.PbdModelConfig_m_angularDampingCoeff_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint m_iterations {
    set {
      UtilsPINVOKE.PbdModelConfig_m_iterations_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = UtilsPINVOKE.PbdModelConfig_m_iterations_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_dt {
    set {
      UtilsPINVOKE.PbdModelConfig_m_dt_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.PbdModelConfig_m_dt_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool m_doPartitioning {
    set {
      UtilsPINVOKE.PbdModelConfig_m_doPartitioning_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.PbdModelConfig_m_doPartitioning_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t m_gravity {
    set {
      UtilsPINVOKE.PbdModelConfig_m_gravity_set(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.PbdModelConfig_m_gravity_get(swigCPtr), true);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PbdFemConstraintConfig m_femParams {
    set {
      UtilsPINVOKE.PbdModelConfig_m_femParams_set(swigCPtr, PbdFemConstraintConfig.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PbdModelConfig_m_femParams_get(swigCPtr);
      PbdFemConstraintConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdFemConstraintConfig(cPtr, true);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PbdConstraint.SolverType m_solverType {
    set {
      UtilsPINVOKE.PbdModelConfig_m_solverType_set(swigCPtr, (int)value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      PbdConstraint.SolverType ret = (PbdConstraint.SolverType)UtilsPINVOKE.PbdModelConfig_m_solverType_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t m_bodyLinearDampingCoeff {
    set {
      UtilsPINVOKE.PbdModelConfig_m_bodyLinearDampingCoeff_set(swigCPtr, SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PbdModelConfig_m_bodyLinearDampingCoeff_get(swigCPtr);
      SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t m_bodyAngularDampingCoeff {
    set {
      UtilsPINVOKE.PbdModelConfig_m_bodyAngularDampingCoeff_set(swigCPtr, SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PbdModelConfig_m_bodyAngularDampingCoeff_get(swigCPtr);
      SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__unordered_mapT_int_double_std__hashT_int_t_t(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_std__shared_ptrT_DataTracker_t m_dataTracker {
    set {
      UtilsPINVOKE.PbdModelConfig_m_dataTracker_set(swigCPtr, SWIGTYPE_p_std__shared_ptrT_DataTracker_t.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PbdModelConfig_m_dataTracker_get(swigCPtr);
      SWIGTYPE_p_std__shared_ptrT_DataTracker_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__shared_ptrT_DataTracker_t(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PbdModelConfig() : this(UtilsPINVOKE.new_PbdModelConfig(), true) {
  }

  public enum ConstraintGenType {
    Custom,
    Distance,
    FemTet,
    Volume,
    Area,
    Bend,
    Dihedral,
    ConstantDensity
  }

}

}
