//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PbdObjectCellRemoval : SceneObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PbdObjectCellRemoval(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.PbdObjectCellRemoval_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PbdObjectCellRemoval obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_PbdObjectCellRemoval(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PbdObjectCellRemoval(PbdObject pbdObj, PbdObjectCellRemoval.OtherMeshUpdateType alsoUpdate) : this(UtilsPINVOKE.new_PbdObjectCellRemoval__SWIG_0(PbdObject.getCPtr(pbdObj), (int)alsoUpdate), true) {
  }

  public PbdObjectCellRemoval(PbdObject pbdObj) : this(UtilsPINVOKE.new_PbdObjectCellRemoval__SWIG_1(PbdObject.getCPtr(pbdObj)), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.PbdObjectCellRemoval_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.PbdObjectCellRemoval_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void removeCellOnApply(int cellId) {
    UtilsPINVOKE.PbdObjectCellRemoval_removeCellOnApply(swigCPtr, cellId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void apply() {
    UtilsPINVOKE.PbdObjectCellRemoval_apply(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorInt getRemovedCells() {
    VectorInt ret = new VectorInt(UtilsPINVOKE.PbdObjectCellRemoval_getRemovedCells(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum OtherMeshUpdateType {
    None = 0,
    Collision = 1,
    VisualReuseVertices = 2,
    VisualSeparateVertices = 4,
    CollisionAndVisualSeparate = Collision|VisualSeparateVertices,
    CollisionAndVisualReused = Collision|VisualReuseVertices
  }

}

}
