//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PbdObject : DynamicObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PbdObject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.PbdObject_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PbdObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_PbdObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PbdObject(string name) : this(UtilsPINVOKE.new_PbdObject__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public PbdObject() : this(UtilsPINVOKE.new_PbdObject__SWIG_1(), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.PbdObject_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.PbdObject_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PbdModel getPbdModel() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdObject_getPbdModel(swigCPtr);
    PbdModel ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdModel(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PbdBody getPbdBody() {
    global::System.IntPtr cPtr = UtilsPINVOKE.PbdObject_getPbdBody(swigCPtr);
    PbdBody ret = (cPtr == global::System.IntPtr.Zero) ? null : new PbdBody(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void setDynamicalModel(AbstractDynamicalModel dynaModel) {
    UtilsPINVOKE.PbdObject_setDynamicalModel(swigCPtr, AbstractDynamicalModel.getCPtr(dynaModel));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updatePhysicsGeometry() {
    UtilsPINVOKE.PbdObject_updatePhysicsGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setBodyFromGeometry() {
    UtilsPINVOKE.PbdObject_setBodyFromGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool initialize() {
    bool ret = UtilsPINVOKE.PbdObject_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void computeCellConstraintMap() {
    UtilsPINVOKE.PbdObject_computeCellConstraintMap(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorConstraint getCellConstraints(int cellId) {
    VectorConstraint ret = new VectorConstraint(UtilsPINVOKE.PbdObject_getCellConstraints(swigCPtr, cellId), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
