//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PbdRigidObjectGrasping : PbdObjectGrasping {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PbdRigidObjectGrasping(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.PbdRigidObjectGrasping_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PbdRigidObjectGrasping obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_PbdRigidObjectGrasping(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PbdRigidObjectGrasping(PbdObject obj1, RigidObject2 obj2) : this(UtilsPINVOKE.new_PbdRigidObjectGrasping(PbdObject.getCPtr(obj1), RigidObject2.getCPtr(obj2)), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.PbdRigidObjectGrasping_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.PbdRigidObjectGrasping_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void updatePicking() {
    UtilsPINVOKE.PbdRigidObjectGrasping_updatePicking(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addPointToPointConstraint(VectorIntPair ptsA, VectorDouble weightsA, VectorIntPair ptsB, VectorDouble weightsB, double stiffnessA, double stiffnessB) {
    UtilsPINVOKE.PbdRigidObjectGrasping_addPointToPointConstraint(swigCPtr, VectorIntPair.getCPtr(ptsA), VectorDouble.getCPtr(weightsA), VectorIntPair.getCPtr(ptsB), VectorDouble.getCPtr(weightsB), stiffnessA, stiffnessB);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void initGraphEdges(SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t source, SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t sink) {
    UtilsPINVOKE.PbdRigidObjectGrasping_initGraphEdges(swigCPtr, SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t.getCPtr(source), SWIGTYPE_p_std__shared_ptrT_imstk__TaskNode_t.getCPtr(sink));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
