//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class PointwiseMap : GeometryMap {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal PointwiseMap(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.PointwiseMap_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PointwiseMap obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_PointwiseMap(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PointwiseMap() : this(UtilsPINVOKE.new_PointwiseMap__SWIG_0(), true) {
  }

  public PointwiseMap(Geometry parent, Geometry child) : this(UtilsPINVOKE.new_PointwiseMap__SWIG_1(Geometry.getCPtr(parent), Geometry.getCPtr(child)), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.PointwiseMap_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.PointwiseMap_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void compute() {
    UtilsPINVOKE.PointwiseMap_compute(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeMap(UnorderedMapIntInt tetVertToSurfVertMap) {
    UtilsPINVOKE.PointwiseMap_computeMap(swigCPtr, UnorderedMapIntInt.getCPtr(tetVertToSurfVertMap));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMap(UnorderedMapIntInt sourceMap) {
    UtilsPINVOKE.PointwiseMap_setMap(swigCPtr, UnorderedMapIntInt.getCPtr(sourceMap));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public UnorderedMapIntInt getMap() {
    UnorderedMapIntInt ret = new UnorderedMapIntInt(UtilsPINVOKE.PointwiseMap_getMap(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addNewUniquePoint(int sourceId, int targetId) {
    UtilsPINVOKE.PointwiseMap_addNewUniquePoint(swigCPtr, sourceId, targetId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getParentVertexId(int childVertexId) {
    int ret = UtilsPINVOKE.PointwiseMap_getParentVertexId(swigCPtr, childVertexId);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTolerance(double tolerance) {
    UtilsPINVOKE.PointwiseMap_setTolerance(swigCPtr, tolerance);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getTolerance() {
    double ret = UtilsPINVOKE.PointwiseMap_getTolerance(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UnorderedMapIntInt m_oneToOneMap {
    set {
      UtilsPINVOKE.PointwiseMap_m_oneToOneMap_set(swigCPtr, UnorderedMapIntInt.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PointwiseMap_m_oneToOneMap_get(swigCPtr);
      UnorderedMapIntInt ret = (cPtr == global::System.IntPtr.Zero) ? null : new UnorderedMapIntInt(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public VectorIntPair m_oneToOneMapVector {
    set {
      UtilsPINVOKE.PointwiseMap_m_oneToOneMapVector_set(swigCPtr, VectorIntPair.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = UtilsPINVOKE.PointwiseMap_m_oneToOneMapVector_get(swigCPtr);
      VectorIntPair ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorIntPair(cPtr, false);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_epsilon {
    set {
      UtilsPINVOKE.PointwiseMap_m_epsilon_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.PointwiseMap_m_epsilon_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
