//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class RenderMaterial : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal RenderMaterial(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.RenderMaterial_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RenderMaterial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_RenderMaterial(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RenderMaterial() : this(UtilsPINVOKE.new_RenderMaterial(), true) {
  }

  public static string modified() {
    string ret = UtilsPINVOKE.RenderMaterial_modified();
    return ret;
  }

  public static string texturesModified() {
    string ret = UtilsPINVOKE.RenderMaterial_texturesModified();
    return ret;
  }

  public string getName() {
    string ret = UtilsPINVOKE.RenderMaterial_getName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setName(string name) {
    UtilsPINVOKE.RenderMaterial_setName(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public RenderMaterial.DisplayMode getDisplayMode() {
    RenderMaterial.DisplayMode ret = (RenderMaterial.DisplayMode)UtilsPINVOKE.RenderMaterial_getDisplayMode(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDisplayMode(RenderMaterial.DisplayMode displayMode) {
    UtilsPINVOKE.RenderMaterial_setDisplayMode(swigCPtr, (int)displayMode);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getLineWidth() {
    double ret = UtilsPINVOKE.RenderMaterial_getLineWidth(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setLineWidth(double width) {
    UtilsPINVOKE.RenderMaterial_setLineWidth(swigCPtr, width);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getPointSize() {
    double ret = UtilsPINVOKE.RenderMaterial_getPointSize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setPointSize(double size) {
    UtilsPINVOKE.RenderMaterial_setPointSize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getBackFaceCulling() {
    bool ret = UtilsPINVOKE.RenderMaterial_getBackFaceCulling(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setBackFaceCulling(bool culling) {
    UtilsPINVOKE.RenderMaterial_setBackFaceCulling(swigCPtr, culling);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void backfaceCullingOn() {
    UtilsPINVOKE.RenderMaterial_backfaceCullingOn(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void backfaceCullingOff() {
    UtilsPINVOKE.RenderMaterial_backfaceCullingOff(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getDiffuseColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getDiffuseColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDiffuseColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setDiffuseColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getSpecularColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getSpecularColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSpecularColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setSpecularColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSpecular() {
    double ret = UtilsPINVOKE.RenderMaterial_getSpecular(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSpecular(double specular) {
    UtilsPINVOKE.RenderMaterial_setSpecular(swigCPtr, specular);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getAmbientColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getAmbientColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setAmbientColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setAmbientColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getMetalness() {
    double ret = UtilsPINVOKE.RenderMaterial_getMetalness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMetalness(double metalness) {
    UtilsPINVOKE.RenderMaterial_setMetalness(swigCPtr, metalness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getAmbient() {
    double ret = UtilsPINVOKE.RenderMaterial_getAmbient(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setAmbient(double ambient) {
    UtilsPINVOKE.RenderMaterial_setAmbient(swigCPtr, ambient);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getDiffuse() {
    double ret = UtilsPINVOKE.RenderMaterial_getDiffuse(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setDiffuse(double diffuse) {
    UtilsPINVOKE.RenderMaterial_setDiffuse(swigCPtr, diffuse);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getSpecularPower() {
    double ret = UtilsPINVOKE.RenderMaterial_getSpecularPower(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setSpecularPower(double p) {
    UtilsPINVOKE.RenderMaterial_setSpecularPower(swigCPtr, p);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getRoughness() {
    double ret = UtilsPINVOKE.RenderMaterial_getRoughness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRoughness(double roughness) {
    UtilsPINVOKE.RenderMaterial_setRoughness(swigCPtr, roughness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getEmissivity() {
    double ret = UtilsPINVOKE.RenderMaterial_getEmissivity(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setEmissivity(double emissivity) {
    UtilsPINVOKE.RenderMaterial_setEmissivity(swigCPtr, emissivity);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getAnisotropy() {
    double ret = UtilsPINVOKE.RenderMaterial_getAnisotropy(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setAnisotropy(double anisotropy) {
    UtilsPINVOKE.RenderMaterial_setAnisotropy(swigCPtr, anisotropy);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getAnisotropyRotation() {
    double ret = UtilsPINVOKE.RenderMaterial_getAnisotropyRotation(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setAnisotropyRotation(double anisotropyRotation) {
    UtilsPINVOKE.RenderMaterial_setAnisotropyRotation(swigCPtr, anisotropyRotation);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getBaseIOR() {
    double ret = UtilsPINVOKE.RenderMaterial_getBaseIOR(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setBaseIOR(double baseIOR) {
    UtilsPINVOKE.RenderMaterial_setBaseIOR(swigCPtr, baseIOR);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getCoatColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getCoatColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCoatColor(Color coatColor) {
    UtilsPINVOKE.RenderMaterial_setCoatColor(swigCPtr, Color.getCPtr(coatColor));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getCoatIOR() {
    double ret = UtilsPINVOKE.RenderMaterial_getCoatIOR(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCoatIOR(double coatIOR) {
    UtilsPINVOKE.RenderMaterial_setCoatIOR(swigCPtr, coatIOR);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getCoatNormalScale() {
    double ret = UtilsPINVOKE.RenderMaterial_getCoatNormalScale(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCoatNormalScale(double coatNormalScale) {
    UtilsPINVOKE.RenderMaterial_setCoatNormalScale(swigCPtr, coatNormalScale);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getCoatRoughness() {
    double ret = UtilsPINVOKE.RenderMaterial_getCoatRoughness(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCoatRoughness(double coatRoughness) {
    UtilsPINVOKE.RenderMaterial_setCoatRoughness(swigCPtr, coatRoughness);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getCoatStrength() {
    double ret = UtilsPINVOKE.RenderMaterial_getCoatStrength(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setCoatStrength(double coatStrength) {
    UtilsPINVOKE.RenderMaterial_setCoatStrength(swigCPtr, coatStrength);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getEdgeTint() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getEdgeTint(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setEdgeTint(Color edgeTint) {
    UtilsPINVOKE.RenderMaterial_setEdgeTint(swigCPtr, Color.getCPtr(edgeTint));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addTexture(Texture texture) {
    UtilsPINVOKE.RenderMaterial_addTexture(swigCPtr, Texture.getCPtr(texture));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeTexture(Texture texture) {
    UtilsPINVOKE.RenderMaterial_removeTexture__SWIG_0(swigCPtr, Texture.getCPtr(texture));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeTexture(Texture.Type type) {
    UtilsPINVOKE.RenderMaterial_removeTexture__SWIG_1(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Texture getTexture(Texture.Type type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.RenderMaterial_getTexture(swigCPtr, (int)type);
    Texture ret = (cPtr == global::System.IntPtr.Zero) ? null : new Texture(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setEdgeVisibility(bool visibility) {
    UtilsPINVOKE.RenderMaterial_setEdgeVisibility(swigCPtr, visibility);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getEdgeVisibility() {
    bool ret = UtilsPINVOKE.RenderMaterial_getEdgeVisibility(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setBlendMode(RenderMaterial.BlendMode blendMode) {
    UtilsPINVOKE.RenderMaterial_setBlendMode(swigCPtr, (int)blendMode);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public RenderMaterial.BlendMode getBlendMode() {
    RenderMaterial.BlendMode ret = (RenderMaterial.BlendMode)UtilsPINVOKE.RenderMaterial_getBlendMode(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RenderMaterial.DisplayMode getRenderMode() {
    RenderMaterial.DisplayMode ret = (RenderMaterial.DisplayMode)UtilsPINVOKE.RenderMaterial_getRenderMode(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RenderMaterial.ShadingModel getShadingModel() {
    RenderMaterial.ShadingModel ret = (RenderMaterial.ShadingModel)UtilsPINVOKE.RenderMaterial_getShadingModel(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setShadingModel(RenderMaterial.ShadingModel model) {
    UtilsPINVOKE.RenderMaterial_setShadingModel(swigCPtr, (int)model);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getOcclusionStrength() {
    double ret = UtilsPINVOKE.RenderMaterial_getOcclusionStrength(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOcclusionStrength(double o) {
    UtilsPINVOKE.RenderMaterial_setOcclusionStrength(swigCPtr, o);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getNormalStrength() {
    double ret = UtilsPINVOKE.RenderMaterial_getNormalStrength(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setNormalStrength(double n) {
    UtilsPINVOKE.RenderMaterial_setNormalStrength(swigCPtr, n);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getEdgeColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getEdgeColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setEdgeColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setEdgeColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getVertexColor() {
    Color ret = new Color(UtilsPINVOKE.RenderMaterial_getVertexColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setVertexColor(Color color) {
    UtilsPINVOKE.RenderMaterial_setVertexColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getOpacity() {
    double ret = UtilsPINVOKE.RenderMaterial_getOpacity(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setOpacity(double opacity) {
    UtilsPINVOKE.RenderMaterial_setOpacity(swigCPtr, opacity);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getBackfaceCulling() {
    bool ret = UtilsPINVOKE.RenderMaterial_getBackfaceCulling(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setBackfaceCulling(bool c) {
    UtilsPINVOKE.RenderMaterial_setBackfaceCulling(swigCPtr, c);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__ColorFunction_t getColorLookupTable() {
    SWIGTYPE_p_std__shared_ptrT_imstk__ColorFunction_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__ColorFunction_t(UtilsPINVOKE.RenderMaterial_getColorLookupTable(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setColorLookupTable(SWIGTYPE_p_std__shared_ptrT_imstk__ColorFunction_t lut) {
    UtilsPINVOKE.RenderMaterial_setColorLookupTable(swigCPtr, SWIGTYPE_p_std__shared_ptrT_imstk__ColorFunction_t.getCPtr(lut));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getScalarVisibility() {
    bool ret = UtilsPINVOKE.RenderMaterial_getScalarVisibility(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setScalarVisibility(bool scalarVisibility) {
    UtilsPINVOKE.RenderMaterial_setScalarVisibility(swigCPtr, scalarVisibility);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getRecomputeVertexNormals() {
    bool ret = UtilsPINVOKE.RenderMaterial_getRecomputeVertexNormals(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRecomputeVertexNormals(bool recomputeVertexNormals) {
    UtilsPINVOKE.RenderMaterial_setRecomputeVertexNormals(swigCPtr, recomputeVertexNormals);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getRenderPointsAsSpheres() {
    bool ret = UtilsPINVOKE.RenderMaterial_getRenderPointsAsSpheres(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRenderPointsAsSpheres(bool renderPointsAsSpheres) {
    UtilsPINVOKE.RenderMaterial_setRenderPointsAsSpheres(swigCPtr, renderPointsAsSpheres);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getIsDynamicMesh() {
    bool ret = UtilsPINVOKE.RenderMaterial_getIsDynamicMesh(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setIsDynamicMesh(bool isDynamicMesh) {
    UtilsPINVOKE.RenderMaterial_setIsDynamicMesh(swigCPtr, isDynamicMesh);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void postModified() {
    UtilsPINVOKE.RenderMaterial_postModified(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public enum DisplayMode {
    Surface,
    Wireframe,
    Points,
    WireframeSurface,
    VolumeRendering,
    Fluid,
    Image,
    SurfaceNormals
  }

  public enum ShadingModel {
    None,
    Phong,
    Gouraud,
    Flat,
    PBR
  }

  public enum BlendMode {
    Alpha,
    Additive,
    MaximumIntensity,
    MinimumIntensity
  }

}

}
