//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class RigidBodyState2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal RigidBodyState2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RigidBodyState2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RigidBodyState2() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_RigidBodyState2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void resize(uint size) {
    UtilsPINVOKE.RigidBodyState2_resize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint size() {
    uint ret = UtilsPINVOKE.RigidBodyState2_size(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorBool getIsStatic() {
    VectorBool ret = new VectorBool(UtilsPINVOKE.RigidBodyState2_getIsStatic__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public VectorDouble getInvMasses() {
    VectorDouble ret = new VectorDouble(UtilsPINVOKE.RigidBodyState2_getInvMasses__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_3_t_Eigen__aligned_allocatorT_imstk__Mat3d_t_t getInvIntertiaTensors() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_3_t_Eigen__aligned_allocatorT_imstk__Mat3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_3_t_Eigen__aligned_allocatorT_imstk__Mat3d_t_t(UtilsPINVOKE.RigidBodyState2_getInvIntertiaTensors__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getPositions() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getPositions__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__QuaternionT_double_t_Eigen__aligned_allocatorT_imstk__Quatd_t_t getOrientations() {
    SWIGTYPE_p_std__vectorT_Eigen__QuaternionT_double_t_Eigen__aligned_allocatorT_imstk__Quatd_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__QuaternionT_double_t_Eigen__aligned_allocatorT_imstk__Quatd_t_t(UtilsPINVOKE.RigidBodyState2_getOrientations__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getVelocities() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getVelocities__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getAngularVelocities() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getAngularVelocities__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getTentatveVelocities() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getTentatveVelocities__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getTentativeAngularVelocities() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getTentativeAngularVelocities__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getForces() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getForces__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t getTorques() {
    SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t ret = new SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t(UtilsPINVOKE.RigidBodyState2_getTorques__SWIG_0(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setState(RigidBodyState2 state) {
    UtilsPINVOKE.RigidBodyState2_setState(swigCPtr, RigidBodyState2.getCPtr(state));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public RigidBodyState2() : this(UtilsPINVOKE.new_RigidBodyState2(), true) {
  }

}

}
