//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class RigidObject2 : DynamicObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal RigidObject2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.RigidObject2_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RigidObject2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_RigidObject2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RigidObject2(string name) : this(UtilsPINVOKE.new_RigidObject2__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public RigidObject2() : this(UtilsPINVOKE.new_RigidObject2__SWIG_1(), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.RigidObject2_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.RigidObject2_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool initialize() {
    bool ret = UtilsPINVOKE.RigidObject2_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RigidBodyModel2 getRigidBodyModel2() {
    global::System.IntPtr cPtr = UtilsPINVOKE.RigidObject2_getRigidBodyModel2(swigCPtr);
    RigidBodyModel2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new RigidBodyModel2(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RigidBody getRigidBody() {
    global::System.IntPtr cPtr = UtilsPINVOKE.RigidObject2_getRigidBody(swigCPtr);
    RigidBody ret = (cPtr == global::System.IntPtr.Zero) ? null : new RigidBody(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void setDynamicalModel(AbstractDynamicalModel dynaModel) {
    UtilsPINVOKE.RigidObject2_setDynamicalModel(swigCPtr, AbstractDynamicalModel.getCPtr(dynaModel));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void updatePhysicsGeometry() {
    UtilsPINVOKE.RigidObject2_updatePhysicsGeometry(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
