//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SceneObjectController : TrackingDeviceControl {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SceneObjectController(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SceneObjectController_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SceneObjectController obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SceneObjectController(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SceneObjectController(string name) : this(UtilsPINVOKE.new_SceneObjectController__SWIG_0(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SceneObjectController() : this(UtilsPINVOKE.new_SceneObjectController__SWIG_1(), true) {
  }

  public void update(double dt) {
    UtilsPINVOKE.SceneObjectController_update(swigCPtr, dt);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SceneObject getControlledObject() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SceneObjectController_getControlledObject(swigCPtr);
    SceneObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new SceneObject(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setControlledObject(SceneObject so) {
    UtilsPINVOKE.SceneObjectController_setControlledObject(swigCPtr, SceneObject.getCPtr(so));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
