//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Scene : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Scene(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Scene_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Scene obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Scene(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Scene(string name, SceneConfig config) : this(UtilsPINVOKE.new_Scene__SWIG_0(name, SceneConfig.getCPtr(config)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Scene(string name) : this(UtilsPINVOKE.new_Scene__SWIG_1(name), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static string configureTaskGraph() {
    string ret = UtilsPINVOKE.Scene_configureTaskGraph();
    return ret;
  }

  public static string modified() {
    string ret = UtilsPINVOKE.Scene_modified();
    return ret;
  }

  public virtual bool initialize() {
    bool ret = UtilsPINVOKE.Scene_initialize(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner, double paddingPercent) {
    UtilsPINVOKE.Scene_computeBoundingBox__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner) {
    UtilsPINVOKE.Scene_computeBoundingBox__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void buildTaskGraph() {
    UtilsPINVOKE.Scene_buildTaskGraph(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initTaskGraph() {
    UtilsPINVOKE.Scene_initTaskGraph(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    UtilsPINVOKE.Scene_reset(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void resetSceneObjects() {
    UtilsPINVOKE.Scene_resetSceneObjects(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void advance(double dt) {
    UtilsPINVOKE.Scene_advance(swigCPtr, dt);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void updateVisuals(double dt) {
    UtilsPINVOKE.Scene_updateVisuals(swigCPtr, dt);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setEnableTaskTiming(bool enabled) {
    UtilsPINVOKE.Scene_setEnableTaskTiming(swigCPtr, enabled);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__unordered_setT_std__shared_ptrT_imstk__Entity_t_t getSceneObjects() {
    SWIGTYPE_p_std__unordered_setT_std__shared_ptrT_imstk__Entity_t_t ret = new SWIGTYPE_p_std__unordered_setT_std__shared_ptrT_imstk__Entity_t_t(UtilsPINVOKE.Scene_getSceneObjects(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Entity getSceneObject(string name) {
    global::System.IntPtr cPtr = UtilsPINVOKE.Scene_getSceneObject(swigCPtr, name);
    Entity ret = (cPtr == global::System.IntPtr.Zero) ? null : new Entity(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addInteraction(Entity interaction) {
    UtilsPINVOKE.Scene_addInteraction(swigCPtr, Entity.getCPtr(interaction));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool hasEntity(Entity entity) {
    bool ret = UtilsPINVOKE.Scene_hasEntity(swigCPtr, Entity.getCPtr(entity));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addSceneObject(Entity entity) {
    UtilsPINVOKE.Scene_addSceneObject(swigCPtr, Entity.getCPtr(entity));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeSceneObject(string name) {
    UtilsPINVOKE.Scene_removeSceneObject__SWIG_0(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeSceneObject(Entity sceneObject) {
    UtilsPINVOKE.Scene_removeSceneObject__SWIG_1(swigCPtr, Entity.getCPtr(sceneObject));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_imstk__Light_t_t getLights() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_imstk__Light_t_t ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_imstk__Light_t_t(UtilsPINVOKE.Scene_getLights(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Light getLight(string lightName) {
    global::System.IntPtr cPtr = UtilsPINVOKE.Scene_getLight(swigCPtr, lightName);
    Light ret = (cPtr == global::System.IntPtr.Zero) ? null : new Light(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addLight(string name, Light newLight) {
    UtilsPINVOKE.Scene_addLight(swigCPtr, name, Light.getCPtr(newLight));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeLight(string lightName) {
    UtilsPINVOKE.Scene_removeLight(swigCPtr, lightName);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setGlobalIBLProbe(SWIGTYPE_p_std__shared_ptrT_imstk__IblProbe_t newIBLProbe) {
    UtilsPINVOKE.Scene_setGlobalIBLProbe(swigCPtr, SWIGTYPE_p_std__shared_ptrT_imstk__IblProbe_t.getCPtr(newIBLProbe));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__IblProbe_t getGlobalIBLProbe() {
    SWIGTYPE_p_std__shared_ptrT_imstk__IblProbe_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__IblProbe_t(UtilsPINVOKE.Scene_getGlobalIBLProbe(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getName() {
    string ret = UtilsPINVOKE.Scene_getName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getUniqueName(string name) {
    string ret = UtilsPINVOKE.Scene_getUniqueName(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t getTaskGraph() {
    SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t ret = new SWIGTYPE_p_std__shared_ptrT_imstk__TaskGraph_t(UtilsPINVOKE.Scene_getTaskGraph(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Camera getActiveCamera() {
    global::System.IntPtr cPtr = UtilsPINVOKE.Scene_getActiveCamera(swigCPtr);
    Camera ret = (cPtr == global::System.IntPtr.Zero) ? null : new Camera(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getCameraName(Camera cam) {
    string ret = UtilsPINVOKE.Scene_getCameraName(swigCPtr, Camera.getCPtr(cam));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Camera getCamera(string name) {
    global::System.IntPtr cPtr = UtilsPINVOKE.Scene_getCamera(swigCPtr, name);
    Camera ret = (cPtr == global::System.IntPtr.Zero) ? null : new Camera(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addCamera(string name, Camera cam) {
    UtilsPINVOKE.Scene_addCamera(swigCPtr, name, Camera.getCPtr(cam));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setActiveCamera(string name) {
    UtilsPINVOKE.Scene_setActiveCamera(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void removeCamera(string name) {
    UtilsPINVOKE.Scene_removeCamera(swigCPtr, name);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addControl(DeviceControl control) {
    UtilsPINVOKE.Scene_addControl(swigCPtr, DeviceControl.getCPtr(control));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getFPS() {
    double ret = UtilsPINVOKE.Scene_getFPS(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getFrameTime() {
    double ret = UtilsPINVOKE.Scene_getFrameTime(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getSceneTime() {
    double ret = UtilsPINVOKE.Scene_getSceneTime(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UnorderedMapStringDouble getTaskComputeTimes() {
    UnorderedMapStringDouble ret = new UnorderedMapStringDouble(UtilsPINVOKE.Scene_getTaskComputeTimes(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void lockComputeTimes() {
    UtilsPINVOKE.Scene_lockComputeTimes(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void unlockComputeTimes() {
    UtilsPINVOKE.Scene_unlockComputeTimes(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SceneConfig getConfig() {
    global::System.IntPtr cPtr = UtilsPINVOKE.Scene_getConfig(swigCPtr);
    SceneConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new SceneConfig(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
