//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SceneManagerWeakPtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SceneManagerWeakPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SceneManagerWeakPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SceneManagerWeakPtr obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SceneManagerWeakPtr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_SceneManagerWeakPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SceneManagerWeakPtr() : this(UtilsPINVOKE.new_SceneManagerWeakPtr__SWIG_0(), true) {
  }

  public SceneManagerWeakPtr(SceneManagerWeakPtr arg0) : this(UtilsPINVOKE.new_SceneManagerWeakPtr__SWIG_1(SceneManagerWeakPtr.getCPtr(arg0)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SceneManagerWeakPtr(SceneManager arg0) : this(UtilsPINVOKE.new_SceneManagerWeakPtr__SWIG_2(SceneManager.getCPtr(arg0)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(SceneManagerWeakPtr arg0) {
    UtilsPINVOKE.SceneManagerWeakPtr_swap(swigCPtr, SceneManagerWeakPtr.getCPtr(arg0));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    UtilsPINVOKE.SceneManagerWeakPtr_reset(swigCPtr);
  }

  public int use_count() {
    int ret = UtilsPINVOKE.SceneManagerWeakPtr_use_count(swigCPtr);
    return ret;
  }

  public bool expired() {
    bool ret = UtilsPINVOKE.SceneManagerWeakPtr_expired(swigCPtr);
    return ret;
  }

  public SceneManager lock_() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SceneManagerWeakPtr_lock_(swigCPtr);
    SceneManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new SceneManager(cPtr, true);
    return ret;
  }

}

}
