//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SceneConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal SceneConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SceneConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SceneConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_SceneConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool trackFPS {
    set {
      UtilsPINVOKE.SceneConfig_trackFPS_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_trackFPS_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool taskParallelizationEnabled {
    set {
      UtilsPINVOKE.SceneConfig_taskParallelizationEnabled_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_taskParallelizationEnabled_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool taskTimingEnabled {
    set {
      UtilsPINVOKE.SceneConfig_taskTimingEnabled_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_taskTimingEnabled_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool writeTaskGraph {
    set {
      UtilsPINVOKE.SceneConfig_writeTaskGraph_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_writeTaskGraph_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool graphReductionEnabled {
    set {
      UtilsPINVOKE.SceneConfig_graphReductionEnabled_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_graphReductionEnabled_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool debugCamBoundingBox {
    set {
      UtilsPINVOKE.SceneConfig_debugCamBoundingBox_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SceneConfig_debugCamBoundingBox_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SceneConfig() : this(UtilsPINVOKE.new_SceneConfig(), true) {
  }

}

}
