//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SelectEnclosedPoints : GeometryAlgorithm {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SelectEnclosedPoints(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SelectEnclosedPoints_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SelectEnclosedPoints obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SelectEnclosedPoints(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SelectEnclosedPoints() : this(UtilsPINVOKE.new_SelectEnclosedPoints(), true) {
  }

  public void setInputMesh(SurfaceMesh inputMesh) {
    UtilsPINVOKE.SelectEnclosedPoints_setInputMesh(swigCPtr, SurfaceMesh.getCPtr(inputMesh));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setInputPoints(PointSet inputPoints) {
    UtilsPINVOKE.SelectEnclosedPoints_setInputPoints(swigCPtr, PointSet.getCPtr(inputPoints));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public PointSet getOutputPoints() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SelectEnclosedPoints_getOutputPoints(swigCPtr);
    PointSet ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointSet(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool getUsePruning() {
    bool ret = UtilsPINVOKE.SelectEnclosedPoints_getUsePruning(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual double getTolerance() {
    double ret = UtilsPINVOKE.SelectEnclosedPoints_getTolerance(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool getInsideOut() {
    bool ret = UtilsPINVOKE.SelectEnclosedPoints_getInsideOut(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DataArrayuc getIsInsideMask() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SelectEnclosedPoints_getIsInsideMask(swigCPtr);
    DataArrayuc ret = (cPtr == global::System.IntPtr.Zero) ? null : new DataArrayuc(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setUsePruning(bool _arg) {
    UtilsPINVOKE.SelectEnclosedPoints_setUsePruning(swigCPtr, _arg);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setTolerance(double _arg) {
    UtilsPINVOKE.SelectEnclosedPoints_setTolerance(swigCPtr, _arg);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setInsideOut(bool _arg) {
    UtilsPINVOKE.SelectEnclosedPoints_setInsideOut(swigCPtr, _arg);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
