//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SignedDistanceField : ImplicitGeometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SignedDistanceField(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SignedDistanceField_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SignedDistanceField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SignedDistanceField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SignedDistanceField(ImageData imageData) : this(UtilsPINVOKE.new_SignedDistanceField(ImageData.getCPtr(imageData)), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.SignedDistanceField_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.SignedDistanceField_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double getFunctionValue(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    double ret = UtilsPINVOKE.SignedDistanceField_getFunctionValue(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getFunctionValueCoord(SWIGTYPE_p_Eigen__MatrixT_int_3_1_t coord) {
    double ret = UtilsPINVOKE.SignedDistanceField_getFunctionValueCoord(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_int_3_1_t.getCPtr(coord));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_6_1_t getBounds() {
    SWIGTYPE_p_Eigen__MatrixT_double_6_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_6_1_t(UtilsPINVOKE.SignedDistanceField_getBounds(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setScale(double scale) {
    UtilsPINVOKE.SignedDistanceField_setScale(swigCPtr, scale);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public double getScale() {
    double ret = UtilsPINVOKE.SignedDistanceField_getScale(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImageData getImage() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SignedDistanceField_getImage(swigCPtr);
    ImageData ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImageData(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t min, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t max, double paddingPercent) {
    UtilsPINVOKE.SignedDistanceField_computeBoundingBox(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(min), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(max), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
