//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SimulationManagerWeakPtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SimulationManagerWeakPtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SimulationManagerWeakPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SimulationManagerWeakPtr obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SimulationManagerWeakPtr() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_SimulationManagerWeakPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SimulationManagerWeakPtr() : this(UtilsPINVOKE.new_SimulationManagerWeakPtr__SWIG_0(), true) {
  }

  public SimulationManagerWeakPtr(SimulationManagerWeakPtr arg0) : this(UtilsPINVOKE.new_SimulationManagerWeakPtr__SWIG_1(SimulationManagerWeakPtr.getCPtr(arg0)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SimulationManagerWeakPtr(SimulationManager arg0) : this(UtilsPINVOKE.new_SimulationManagerWeakPtr__SWIG_2(SimulationManager.getCPtr(arg0)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void swap(SimulationManagerWeakPtr arg0) {
    UtilsPINVOKE.SimulationManagerWeakPtr_swap(swigCPtr, SimulationManagerWeakPtr.getCPtr(arg0));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    UtilsPINVOKE.SimulationManagerWeakPtr_reset(swigCPtr);
  }

  public int use_count() {
    int ret = UtilsPINVOKE.SimulationManagerWeakPtr_use_count(swigCPtr);
    return ret;
  }

  public bool expired() {
    bool ret = UtilsPINVOKE.SimulationManagerWeakPtr_expired(swigCPtr);
    return ret;
  }

  public SimulationManager lock_() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SimulationManagerWeakPtr_lock_(swigCPtr);
    SimulationManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new SimulationManager(cPtr, true);
    return ret;
  }

}

}
