//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SphBoundaryConditions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SphBoundaryConditions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SphBoundaryConditions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SphBoundaryConditions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SphBoundaryConditions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_SphBoundaryConditions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SphBoundaryConditions(SWIGTYPE_p_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t inletCoords, SWIGTYPE_p_std__vectorT_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t_t outletCoords, SWIGTYPE_p_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t fluidCoords, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t inletNormal, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t outletNormals, double inletRadius, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t inletCenterPt, double inletFlowRate, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t mainParticlePositions, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t wallParticlePositions) : this(UtilsPINVOKE.new_SphBoundaryConditions(SWIGTYPE_p_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t.getCPtr(inletCoords), SWIGTYPE_p_std__vectorT_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t_t.getCPtr(outletCoords), SWIGTYPE_p_std__pairT_Eigen__MatrixT_double_3_1_t_Eigen__MatrixT_double_3_1_t_t.getCPtr(fluidCoords), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(inletNormal), SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(outletNormals), inletRadius, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(inletCenterPt), inletFlowRate, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(mainParticlePositions), SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(wallParticlePositions)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isInInletDomain(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t position) {
    bool ret = UtilsPINVOKE.SphBoundaryConditions_isInInletDomain(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(position));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isInOutletDomain(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t position) {
    bool ret = UtilsPINVOKE.SphBoundaryConditions_isInOutletDomain(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(position));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isInFluidDomain(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t position) {
    bool ret = UtilsPINVOKE.SphBoundaryConditions_isInFluidDomain(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(position));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setParticleTypes(SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t mainParticlePositions, uint numWallParticles) {
    UtilsPINVOKE.SphBoundaryConditions_setParticleTypes(swigCPtr, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(mainParticlePositions), numWallParticles);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_imstk__SphBoundaryConditions__ParticleType_t getParticleTypes() {
    SWIGTYPE_p_std__vectorT_imstk__SphBoundaryConditions__ParticleType_t ret = new SWIGTYPE_p_std__vectorT_imstk__SphBoundaryConditions__ParticleType_t(UtilsPINVOKE.SphBoundaryConditions_getParticleTypes(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getBufferCoord() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_getBufferCoord(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t computeParabolicInletVelocity(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t position) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_computeParabolicInletVelocity(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(position)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addBoundaryParticles(SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t mainParticlePositions, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t wallParticlePositions) {
    UtilsPINVOKE.SphBoundaryConditions_addBoundaryParticles(swigCPtr, SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(mainParticlePositions), SWIGTYPE_p_std__vectorT_Eigen__MatrixT_double_3_1_t_Eigen__aligned_allocatorT_imstk__Vec3d_t_t.getCPtr(wallParticlePositions));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setInletVelocity(double flowRate) {
    UtilsPINVOKE.SphBoundaryConditions_setInletVelocity(swigCPtr, flowRate);
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getInletCoord() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_getInletCoord(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getInletVelocity() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_getInletVelocity(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t getInletNormal() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_getInletNormal(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_size_t_t getBufferIndices() {
    SWIGTYPE_p_std__vectorT_size_t_t ret = new SWIGTYPE_p_std__vectorT_size_t_t(UtilsPINVOKE.SphBoundaryConditions_getBufferIndices(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t placeParticleAtInlet(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t position) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphBoundaryConditions_placeParticleAtInlet(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(position)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum ParticleType {
    Fluid,
    Wall,
    Inlet,
    Outlet,
    Buffer
  }

}

}
