//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Sphere : AnalyticalGeometry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Sphere(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Sphere_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Sphere obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Sphere(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Sphere(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos, double radius) : this(UtilsPINVOKE.new_Sphere__SWIG_0(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos), radius), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Sphere(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) : this(UtilsPINVOKE.new_Sphere__SWIG_1(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Sphere() : this(UtilsPINVOKE.new_Sphere__SWIG_2(), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.Sphere_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.Sphere_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void print() {
    UtilsPINVOKE.Sphere_print(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getVolume() {
    double ret = UtilsPINVOKE.Sphere_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getRadius(Geometry.DataType type) {
    double ret = UtilsPINVOKE.Sphere_getRadius__SWIG_0(swigCPtr, (int)type);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getRadius() {
    double ret = UtilsPINVOKE.Sphere_getRadius__SWIG_1(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setRadius(double r) {
    UtilsPINVOKE.Sphere_setRadius(swigCPtr, r);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner, double paddingPercent) {
    UtilsPINVOKE.Sphere_computeBoundingBox__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner), paddingPercent);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void computeBoundingBox(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t lowerCorner, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t upperCorner) {
    UtilsPINVOKE.Sphere_computeBoundingBox__SWIG_1(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(lowerCorner), SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(upperCorner));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getFunctionValue(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    double ret = UtilsPINVOKE.Sphere_getFunctionValue(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void updatePostTransformData() {
    UtilsPINVOKE.Sphere_updatePostTransformData(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
