//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SphModelConfig : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal SphModelConfig(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SphModelConfig obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SphModelConfig() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          UtilsPINVOKE.delete_SphModelConfig(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SphModelConfig(double particleRadius) : this(UtilsPINVOKE.new_SphModelConfig__SWIG_0(particleRadius), true) {
  }

  public SphModelConfig(double particleRadius, double speedOfSound, double restDensity) : this(UtilsPINVOKE.new_SphModelConfig__SWIG_1(particleRadius, speedOfSound, restDensity), true) {
  }

  public double m_minTimestep {
    set {
      UtilsPINVOKE.SphModelConfig_m_minTimestep_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_minTimestep_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_maxTimestep {
    set {
      UtilsPINVOKE.SphModelConfig_m_maxTimestep_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_maxTimestep_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_cflFactor {
    set {
      UtilsPINVOKE.SphModelConfig_m_cflFactor_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_cflFactor_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_particleRadius {
    set {
      UtilsPINVOKE.SphModelConfig_m_particleRadius_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_particleRadius_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_particleRadiusSqr {
    set {
      UtilsPINVOKE.SphModelConfig_m_particleRadiusSqr_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_particleRadiusSqr_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_restDensity {
    set {
      UtilsPINVOKE.SphModelConfig_m_restDensity_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_restDensity_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_restDensitySqr {
    set {
      UtilsPINVOKE.SphModelConfig_m_restDensitySqr_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_restDensitySqr_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_restDensityInv {
    set {
      UtilsPINVOKE.SphModelConfig_m_restDensityInv_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_restDensityInv_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_particleMass {
    set {
      UtilsPINVOKE.SphModelConfig_m_particleMass_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_particleMass_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_particleMassScale {
    set {
      UtilsPINVOKE.SphModelConfig_m_particleMassScale_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_particleMassScale_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_eta {
    set {
      UtilsPINVOKE.SphModelConfig_m_eta_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_eta_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool m_bNormalizeDensity {
    set {
      UtilsPINVOKE.SphModelConfig_m_bNormalizeDensity_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SphModelConfig_m_bNormalizeDensity_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool m_bDensityWithBoundary {
    set {
      UtilsPINVOKE.SphModelConfig_m_bDensityWithBoundary_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = UtilsPINVOKE.SphModelConfig_m_bDensityWithBoundary_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_pressureStiffness {
    set {
      UtilsPINVOKE.SphModelConfig_m_pressureStiffness_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_pressureStiffness_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_dynamicViscosityCoeff {
    set {
      UtilsPINVOKE.SphModelConfig_m_dynamicViscosityCoeff_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_dynamicViscosityCoeff_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_viscosityBoundary {
    set {
      UtilsPINVOKE.SphModelConfig_m_viscosityBoundary_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_viscosityBoundary_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_surfaceTensionStiffness {
    set {
      UtilsPINVOKE.SphModelConfig_m_surfaceTensionStiffness_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_surfaceTensionStiffness_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_frictionBoundary {
    set {
      UtilsPINVOKE.SphModelConfig_m_frictionBoundary_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_frictionBoundary_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_kernelOverParticleRadiusRatio {
    set {
      UtilsPINVOKE.SphModelConfig_m_kernelOverParticleRadiusRatio_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_kernelOverParticleRadiusRatio_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_kernelRadius {
    set {
      UtilsPINVOKE.SphModelConfig_m_kernelRadius_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_kernelRadius_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_kernelRadiusSqr {
    set {
      UtilsPINVOKE.SphModelConfig_m_kernelRadiusSqr_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_kernelRadiusSqr_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t m_gravity {
    set {
      UtilsPINVOKE.SphModelConfig_m_gravity_set(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(value));
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SphModelConfig_m_gravity_get(swigCPtr), true);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double m_speedOfSound {
    set {
      UtilsPINVOKE.SphModelConfig_m_speedOfSound_set(swigCPtr, value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = UtilsPINVOKE.SphModelConfig_m_speedOfSound_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NeighborSearch.Method m_neighborSearchMethod {
    set {
      UtilsPINVOKE.SphModelConfig_m_neighborSearchMethod_set(swigCPtr, (int)value);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      NeighborSearch.Method ret = (NeighborSearch.Method)UtilsPINVOKE.SphModelConfig_m_neighborSearchMethod_get(swigCPtr);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
