//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SurfaceMesh : CellMesh3 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SurfaceMesh(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SurfaceMesh_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SurfaceMesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SurfaceMesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SurfaceMesh() : this(UtilsPINVOKE.new_SurfaceMesh(), true) {
  }

  public new static string getStaticTypeName() {
    string ret = UtilsPINVOKE.SurfaceMesh_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.SurfaceMesh_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void initialize(VecDataArray3d vertices, VecDataArray3i triangleIndices, bool computeDerivedData) {
    UtilsPINVOKE.SurfaceMesh_initialize__SWIG_0(swigCPtr, VecDataArray3d.getCPtr(vertices), VecDataArray3i.getCPtr(triangleIndices), computeDerivedData);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public new void initialize(VecDataArray3d vertices, VecDataArray3i triangleIndices) {
    UtilsPINVOKE.SurfaceMesh_initialize__SWIG_1(swigCPtr, VecDataArray3d.getCPtr(vertices), VecDataArray3i.getCPtr(triangleIndices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initialize(VecDataArray3d vertices, VecDataArray3i triangleIndices, VecDataArray3d normals, bool computeDerivedData) {
    UtilsPINVOKE.SurfaceMesh_initialize__SWIG_2(swigCPtr, VecDataArray3d.getCPtr(vertices), VecDataArray3i.getCPtr(triangleIndices), VecDataArray3d.getCPtr(normals), computeDerivedData);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initialize(VecDataArray3d vertices, VecDataArray3i triangleIndices, VecDataArray3d normals) {
    UtilsPINVOKE.SurfaceMesh_initialize__SWIG_3(swigCPtr, VecDataArray3d.getCPtr(vertices), VecDataArray3i.getCPtr(triangleIndices), VecDataArray3d.getCPtr(normals));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeTrianglesNormals() {
    UtilsPINVOKE.SurfaceMesh_computeTrianglesNormals(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeTriangleTangents() {
    UtilsPINVOKE.SurfaceMesh_computeTriangleTangents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeVertexNormals() {
    UtilsPINVOKE.SurfaceMesh_computeVertexNormals(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeVertexTangents() {
    UtilsPINVOKE.SurfaceMesh_computeVertexTangents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t computeBarycentricWeights(int tetId, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t pos) {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.SurfaceMesh_computeBarycentricWeights(swigCPtr, tetId, SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(pos)), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void optimizeForDataLocality() {
    UtilsPINVOKE.SurfaceMesh_optimizeForDataLocality(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void flipNormals() {
    UtilsPINVOKE.SurfaceMesh_flipNormals(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void correctWindingOrder() {
    UtilsPINVOKE.SurfaceMesh_correctWindingOrder(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void computeUVSeamVertexGroups() {
    UtilsPINVOKE.SurfaceMesh_computeUVSeamVertexGroups(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getVolume() {
    double ret = UtilsPINVOKE.SurfaceMesh_getVolume(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getNumTriangles() {
    int ret = UtilsPINVOKE.SurfaceMesh_getNumTriangles(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTriangleIndices(VecDataArray3i indices) {
    UtilsPINVOKE.SurfaceMesh_setTriangleIndices(swigCPtr, VecDataArray3i.getCPtr(indices));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VecDataArray3i getTriangleIndices() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SurfaceMesh_getTriangleIndices(swigCPtr);
    VecDataArray3i ret = (cPtr == global::System.IntPtr.Zero) ? null : new VecDataArray3i(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
