//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SurfaceMeshTextureProject : GeometryAlgorithm {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SurfaceMeshTextureProject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SurfaceMeshTextureProject_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SurfaceMeshTextureProject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SurfaceMeshTextureProject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SurfaceMeshTextureProject() : this(UtilsPINVOKE.new_SurfaceMeshTextureProject(), true) {
  }

  public void setSourceMesh(SurfaceMesh surfMesh) {
    UtilsPINVOKE.SurfaceMeshTextureProject_setSourceMesh(swigCPtr, SurfaceMesh.getCPtr(surfMesh));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setDestMesh(SurfaceMesh destMesh) {
    UtilsPINVOKE.SurfaceMeshTextureProject_setDestMesh(swigCPtr, SurfaceMesh.getCPtr(destMesh));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SurfaceMesh getOutputMesh() {
    global::System.IntPtr cPtr = UtilsPINVOKE.SurfaceMeshTextureProject_getOutputMesh(swigCPtr);
    SurfaceMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new SurfaceMesh(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
