//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class SurfaceMeshToSurfaceMeshCD : CollisionDetectionAlgorithm {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal SurfaceMeshToSurfaceMeshCD(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.SurfaceMeshToSurfaceMeshCD_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SurfaceMeshToSurfaceMeshCD obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_SurfaceMeshToSurfaceMeshCD(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SurfaceMeshToSurfaceMeshCD() : this(UtilsPINVOKE.new_SurfaceMeshToSurfaceMeshCD(), true) {
  }

  public static string getStaticTypeName() {
    string ret = UtilsPINVOKE.SurfaceMeshToSurfaceMeshCD_getStaticTypeName();
    return ret;
  }

  public override string getTypeName() {
    string ret = UtilsPINVOKE.SurfaceMeshToSurfaceMeshCD_getTypeName(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setMaxNumContacts(int maxNumContacts) {
    UtilsPINVOKE.SurfaceMeshToSurfaceMeshCD_setMaxNumContacts(swigCPtr, maxNumContacts);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getMaxNumContacts() {
    int ret = UtilsPINVOKE.SurfaceMeshToSurfaceMeshCD_getMaxNumContacts(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
