//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Texture : EventObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Texture(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.Texture_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Texture obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_Texture(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Texture(string path, Texture.Type type) : this(UtilsPINVOKE.new_Texture__SWIG_0(path, (int)type), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Texture(string path) : this(UtilsPINVOKE.new_Texture__SWIG_1(path), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Texture() : this(UtilsPINVOKE.new_Texture__SWIG_2(), true) {
  }

  public Texture(ImageData imageTex, Texture.Type type) : this(UtilsPINVOKE.new_Texture__SWIG_3(ImageData.getCPtr(imageTex), (int)type), true) {
  }

  public Texture(ImageData imageTex) : this(UtilsPINVOKE.new_Texture__SWIG_4(ImageData.getCPtr(imageTex)), true) {
  }

  public static string modified() {
    string ret = UtilsPINVOKE.Texture_modified();
    return ret;
  }

  public void postModified() {
    UtilsPINVOKE.Texture_postModified(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Texture.Type getType() {
    Texture.Type ret = (Texture.Type)UtilsPINVOKE.Texture_getType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getPath() {
    string ret = UtilsPINVOKE.Texture_getPath(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Texture.FileType getFileType() {
    Texture.FileType ret = (Texture.FileType)UtilsPINVOKE.Texture_getFileType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getMipmapsEnabled() {
    bool ret = UtilsPINVOKE.Texture_getMipmapsEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Texture.WrapType getWrapType() {
    Texture.WrapType ret = (Texture.WrapType)UtilsPINVOKE.Texture_getWrapType(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setWrapType(Texture.WrapType repeat) {
    UtilsPINVOKE.Texture_setWrapType(swigCPtr, (int)repeat);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Color getBorderColor() {
    Color ret = new Color(UtilsPINVOKE.Texture_getBorderColor(swigCPtr), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setBorderColor(Color color) {
    UtilsPINVOKE.Texture_setBorderColor(swigCPtr, Color.getCPtr(color));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isAnisotropyEnabled() {
    bool ret = UtilsPINVOKE.Texture_isAnisotropyEnabled(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double getAnisotropyFactor() {
    double ret = UtilsPINVOKE.Texture_getAnisotropyFactor(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setImageData(ImageData imgData) {
    UtilsPINVOKE.Texture_setImageData(swigCPtr, ImageData.getCPtr(imgData));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setInterpolation(bool interpolation) {
    UtilsPINVOKE.Texture_setInterpolation(swigCPtr, interpolation);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool getInterpolation() {
    bool ret = UtilsPINVOKE.Texture_getInterpolation(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ImageData getImageData() {
    global::System.IntPtr cPtr = UtilsPINVOKE.Texture_getImageData(swigCPtr);
    ImageData ret = (cPtr == global::System.IntPtr.Zero) ? null : new ImageData(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum Type {
    Diffuse = 0,
    Normal,
    Roughness,
    Metalness,
    SubsurfaceScattering,
    AmbientOcclusion,
    Cavity,
    Cubemap,
    IrradianceCubeMap,
    RadianceCubeMap,
    ORM,
    BRDF_LUT,
    Emissive,
    Anistropy,
    CoatNormal,
    None
  }

  public enum FileType {
    Unknown,
    Bmp,
    Png,
    Jpg,
    Dds
  }

  public enum WrapType {
    CLAMP_TO_EDGE,
    CLAMP_TO_BORDER,
    REPEAT
  }

}

}
