//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Vec3uc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec3uc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec3uc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vec3uc obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vec3uc() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_Vec3uc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    /* public unsigned char this[int i] { */
    public byte this[int i]
    {
        get => getValue(i);
        set => Utils.ucharPtr_assign(setValue(i), value);
    }

    public static Vec3uc operator + (Vec3uc u, Vec3uc v)
    {
        return Utils.vec_add_3uc(u, v);
    }
    public static Vec3uc operator - (Vec3uc u, Vec3uc v)
    {
        return Utils.vec_subtract_3uc(u, v);
    }
    public static Vec3uc operator * (Vec3uc v, byte c)
    {
        return Utils.vec_scale_3uc(v, c);
    }

    public static Vec3uc operator * (byte c, Vec3uc v)
    {
        return Utils.vec_scale_3uc(v, c);
    }

    public static implicit operator SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t (Vec3uc v)
    {
        return v.get(); 
    }

    public static implicit operator Vec3uc(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t eigen_v)
    {
        return Utils.vec_from_eigen_3uc(eigen_v);
    }

  public Vec3uc(Vec3uc other) : this(UtilsPINVOKE.new_Vec3uc__SWIG_0(Vec3uc.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec3uc() : this(UtilsPINVOKE.new_Vec3uc__SWIG_1(), true) {
  }

  public Vec3uc(byte t0, byte t1) : this(UtilsPINVOKE.new_Vec3uc__SWIG_2(t0, t1), true) {
  }

  public Vec3uc(byte t0, byte t1, byte t2) : this(UtilsPINVOKE.new_Vec3uc__SWIG_3(t0, t1, t2), true) {
  }

  public Vec3uc(byte t0, byte t1, byte t2, byte t3) : this(UtilsPINVOKE.new_Vec3uc__SWIG_4(t0, t1, t2, t3), true) {
  }

  public Vec3uc(byte t0, byte t1, byte t2, byte t3, byte t4, byte t5) : this(UtilsPINVOKE.new_Vec3uc__SWIG_5(t0, t1, t2, t3, t4, t5), true) {
  }

  public Vec3uc(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t other) : this(UtilsPINVOKE.new_Vec3uc__SWIG_6(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  private SWIGTYPE_p_unsigned_char setValue(int pos) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(UtilsPINVOKE.Vec3uc_setValue(swigCPtr, pos), false);
    return ret;
  }

  private byte getValue(int pos) {
    byte ret = UtilsPINVOKE.Vec3uc_getValue(swigCPtr, pos);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t get() {
    SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t(UtilsPINVOKE.Vec3uc_get(swigCPtr), false);
    return ret;
  }

}

}
