//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Vec3d : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec3d(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec3d obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vec3d obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vec3d() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_Vec3d(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    public double this[int i]
    {
        get => getValue(i);
        set => Utils.doublePtr_assign(setValue(i), value);
    }

    public static Vec3d operator + (Vec3d u, Vec3d v)
    {
        return Utils.vec_add_3d(u, v);
    }
    public static Vec3d operator - (Vec3d u, Vec3d v)
    {
        return Utils.vec_subtract_3d(u, v);
    }
    public static Vec3d operator * (Vec3d v, double c)
    {
        return Utils.vec_scale_3d(v, c);
    }

    public static Vec3d operator * (double c, Vec3d v)
    {
        return Utils.vec_scale_3d(v, c);
    }

    public static Vec3d operator / (Vec3d v, double c)
    {
        return Utils.vec_scale_3d(v, 1.0/c);
    }

    public static Vec3d operator / (double c, Vec3d v)
    {
        return Utils.vec_scale_3d(v, 1.0 / c);
    }

    public static implicit operator SWIGTYPE_p_Eigen__MatrixT_double_3_1_t (Vec3d v)
    {
        return v.get(); 
    }

    public static implicit operator Vec3d(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t eigen_v)
    {
        return Utils.vec_from_eigen_3d(eigen_v);
    }
    public Vec3d normalized()
    {
        double nrm= getValue(0) * getValue(0) + getValue(1) * getValue(1) + getValue(2) * getValue(2);
        return this / System.Math.Sqrt(nrm);
    }

  public Vec3d(Vec3d other) : this(UtilsPINVOKE.new_Vec3d__SWIG_0(Vec3d.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec3d() : this(UtilsPINVOKE.new_Vec3d__SWIG_1(), true) {
  }

  public Vec3d(double t0, double t1) : this(UtilsPINVOKE.new_Vec3d__SWIG_2(t0, t1), true) {
  }

  public Vec3d(double t0, double t1, double t2) : this(UtilsPINVOKE.new_Vec3d__SWIG_3(t0, t1, t2), true) {
  }

  public Vec3d(double t0, double t1, double t2, double t3) : this(UtilsPINVOKE.new_Vec3d__SWIG_4(t0, t1, t2, t3), true) {
  }

  public Vec3d(double t0, double t1, double t2, double t3, double t4, double t5) : this(UtilsPINVOKE.new_Vec3d__SWIG_5(t0, t1, t2, t3, t4, t5), true) {
  }

  public Vec3d(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t other) : this(UtilsPINVOKE.new_Vec3d__SWIG_6(SWIGTYPE_p_Eigen__MatrixT_double_3_1_t.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  private SWIGTYPE_p_double setValue(int pos) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(UtilsPINVOKE.Vec3d_setValue(swigCPtr, pos), false);
    return ret;
  }

  private double getValue(int pos) {
    double ret = UtilsPINVOKE.Vec3d_getValue(swigCPtr, pos);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_3_1_t get() {
    SWIGTYPE_p_Eigen__MatrixT_double_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_3_1_t(UtilsPINVOKE.Vec3d_get(swigCPtr), false);
    return ret;
  }

}

}
