//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class Vec4i : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec4i(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec4i obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vec4i obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vec4i() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_Vec4i(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    public int this[int i]
    {
        get => getValue(i);
        set => Utils.intPtr_assign(setValue(i), value);
    }

    public static Vec4i operator + (Vec4i u, Vec4i v)
    {
        return Utils.vec_add_4i(u, v);
    }
    public static Vec4i operator - (Vec4i u, Vec4i v)
    {
        return Utils.vec_subtract_4i(u, v);
    }
    public static Vec4i operator * (Vec4i v, int c)
    {
        return Utils.vec_scale_4i(v, c);
    }

    public static Vec4i operator * (int c, Vec4i v)
    {
        return Utils.vec_scale_4i(v, c);
    }

    public static implicit operator SWIGTYPE_p_Eigen__MatrixT_int_4_1_t (Vec4i v)
    {
        return v.get(); 
    }

    public static implicit operator Vec4i(SWIGTYPE_p_Eigen__MatrixT_int_4_1_t eigen_v)
    {
        return Utils.vec_from_eigen_4i(eigen_v);
    }

  public Vec4i(Vec4i other) : this(UtilsPINVOKE.new_Vec4i__SWIG_0(Vec4i.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec4i() : this(UtilsPINVOKE.new_Vec4i__SWIG_1(), true) {
  }

  public Vec4i(int t0, int t1) : this(UtilsPINVOKE.new_Vec4i__SWIG_2(t0, t1), true) {
  }

  public Vec4i(int t0, int t1, int t2) : this(UtilsPINVOKE.new_Vec4i__SWIG_3(t0, t1, t2), true) {
  }

  public Vec4i(int t0, int t1, int t2, int t3) : this(UtilsPINVOKE.new_Vec4i__SWIG_4(t0, t1, t2, t3), true) {
  }

  public Vec4i(int t0, int t1, int t2, int t3, int t4, int t5) : this(UtilsPINVOKE.new_Vec4i__SWIG_5(t0, t1, t2, t3, t4, t5), true) {
  }

  public Vec4i(SWIGTYPE_p_Eigen__MatrixT_int_4_1_t other) : this(UtilsPINVOKE.new_Vec4i__SWIG_6(SWIGTYPE_p_Eigen__MatrixT_int_4_1_t.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  private SWIGTYPE_p_int setValue(int pos) {
    SWIGTYPE_p_int ret = new SWIGTYPE_p_int(UtilsPINVOKE.Vec4i_setValue(swigCPtr, pos), false);
    return ret;
  }

  private int getValue(int pos) {
    int ret = UtilsPINVOKE.Vec4i_getValue(swigCPtr, pos);
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_int_4_1_t get() {
    SWIGTYPE_p_Eigen__MatrixT_int_4_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_int_4_1_t(UtilsPINVOKE.Vec4i_get(swigCPtr), false);
    return ret;
  }

}

}
