//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class VecDataArray2d : DataArrayd {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal VecDataArray2d(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.VecDataArray2d_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VecDataArray2d obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_VecDataArray2d(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

    public Vec2d this[uint i]
    {
        get => Utils.vec_from_eigen_2d(getValue(i));
        set => Utils.vec_to_eigen_2d(setValue(i), value);
    }
    public void push_back(Vec2d v)
    {
        Utils.vecdataarray_push_back_2d(this, v);
    }

  public VecDataArray2d() : this(UtilsPINVOKE.new_VecDataArray2d__SWIG_0(), true) {
  }

  public VecDataArray2d(int size) : this(UtilsPINVOKE.new_VecDataArray2d__SWIG_1(size), true) {
  }

  public VecDataArray2d(SWIGTYPE_p_std__initializer_listT_Eigen__MatrixT_double_2_1_t_t list) : this(UtilsPINVOKE.new_VecDataArray2d__SWIG_2(SWIGTYPE_p_std__initializer_listT_Eigen__MatrixT_double_2_1_t_t.getCPtr(list)), true) {
  }

  public VecDataArray2d(VecDataArray2d other) : this(UtilsPINVOKE.new_VecDataArray2d__SWIG_3(VecDataArray2d.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override AbstractDataArray cast(byte type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.VecDataArray2d_cast(swigCPtr, type);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void resize(int size) {
    UtilsPINVOKE.VecDataArray2d_resize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void fill(SWIGTYPE_p_Eigen__MatrixT_double_2_1_t val) {
    UtilsPINVOKE.VecDataArray2d_fill(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public new int size() {
    int ret = UtilsPINVOKE.VecDataArray2d_size(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void squeeze() {
    UtilsPINVOKE.VecDataArray2d_squeeze(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(SWIGTYPE_p_Eigen__MatrixT_double_2_1_t val) {
    UtilsPINVOKE.VecDataArray2d_push_back__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator begin() {
    SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator ret = new SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator(UtilsPINVOKE.VecDataArray2d_begin(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator end() {
    SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator ret = new SWIGTYPE_p_imstk__VecDataArrayT_double_2_t__const_iterator(UtilsPINVOKE.VecDataArray2d_end(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void reserve(int size) {
    UtilsPINVOKE.VecDataArray2d_reserve(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  new public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t getPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.VecDataArray2d_getPointer(swigCPtr);
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t setValue(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(UtilsPINVOKE.VecDataArray2d_setValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t getValue(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(UtilsPINVOKE.VecDataArray2d_getValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_double_2_1_t at(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_double_2_1_t(UtilsPINVOKE.VecDataArray2d_at__SWIG_0(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void erase(int vecPos) {
    UtilsPINVOKE.VecDataArray2d_erase(swigCPtr, vecPos);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setData(SWIGTYPE_p_Eigen__MatrixT_double_2_1_t ptr, int size) {
    UtilsPINVOKE.VecDataArray2d_setData(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_double_2_1_t.getCPtr(ptr), size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getNumberOfComponents() {
    int ret = UtilsPINVOKE.VecDataArray2d_getNumberOfComponents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setValues(double[] val) {
    fixed ( double* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray2d_setValues__SWIG_0(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void setValues(double[] val, int n) {
    fixed ( double* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray2d_setValues__SWIG_1(swigCPtr, (global::System.IntPtr)swig_ptrTo_val, n);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void getValues(double[] val) {
    fixed ( double* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray2d_getValues(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public static readonly int NumComponents = UtilsPINVOKE.VecDataArray2d_NumComponents_get();
}

}
