//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class VecDataArray3uc : DataArrayuc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal VecDataArray3uc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(UtilsPINVOKE.VecDataArray3uc_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VecDataArray3uc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          UtilsPINVOKE.delete_VecDataArray3uc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

    public Vec3uc this[uint i]
    {
        get => Utils.vec_from_eigen_3uc(getValue(i));
        set => Utils.vec_to_eigen_3uc(setValue(i), value);
    }
    public void push_back(Vec3uc v)
    {
        Utils.vecdataarray_push_back_3uc(this, v);
    }

  public VecDataArray3uc() : this(UtilsPINVOKE.new_VecDataArray3uc__SWIG_0(), true) {
  }

  public VecDataArray3uc(int size) : this(UtilsPINVOKE.new_VecDataArray3uc__SWIG_1(size), true) {
  }

  public VecDataArray3uc(SWIGTYPE_p_std__initializer_listT_Eigen__MatrixT_unsigned_char_3_1_t_t list) : this(UtilsPINVOKE.new_VecDataArray3uc__SWIG_2(SWIGTYPE_p_std__initializer_listT_Eigen__MatrixT_unsigned_char_3_1_t_t.getCPtr(list)), true) {
  }

  public VecDataArray3uc(VecDataArray3uc other) : this(UtilsPINVOKE.new_VecDataArray3uc__SWIG_3(VecDataArray3uc.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override AbstractDataArray cast(byte type) {
    global::System.IntPtr cPtr = UtilsPINVOKE.VecDataArray3uc_cast(swigCPtr, type);
    AbstractDataArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractDataArray(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void resize(int size) {
    UtilsPINVOKE.VecDataArray3uc_resize(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void fill(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t val) {
    UtilsPINVOKE.VecDataArray3uc_fill(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t.getCPtr(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public new int size() {
    int ret = UtilsPINVOKE.VecDataArray3uc_size(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void squeeze() {
    UtilsPINVOKE.VecDataArray3uc_squeeze(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void push_back(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t val) {
    UtilsPINVOKE.VecDataArray3uc_push_back__SWIG_0(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t.getCPtr(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator begin() {
    SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator ret = new SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator(UtilsPINVOKE.VecDataArray3uc_begin(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator end() {
    SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator ret = new SWIGTYPE_p_imstk__VecDataArrayT_unsigned_char_3_t__const_iterator(UtilsPINVOKE.VecDataArray3uc_end(swigCPtr), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void reserve(int size) {
    UtilsPINVOKE.VecDataArray3uc_reserve(swigCPtr, size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  new public SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t getPointer() {
    global::System.IntPtr cPtr = UtilsPINVOKE.VecDataArray3uc_getPointer(swigCPtr);
    SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t(cPtr, false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t setValue(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t(UtilsPINVOKE.VecDataArray3uc_setValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t getValue(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t(UtilsPINVOKE.VecDataArray3uc_getValue(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t at(uint pos) {
    SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ret = new SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t(UtilsPINVOKE.VecDataArray3uc_at__SWIG_0(swigCPtr, pos), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void erase(int vecPos) {
    UtilsPINVOKE.VecDataArray3uc_erase(swigCPtr, vecPos);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setData(SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t ptr, int size) {
    UtilsPINVOKE.VecDataArray3uc_setData(swigCPtr, SWIGTYPE_p_Eigen__MatrixT_unsigned_char_3_1_t.getCPtr(ptr), size);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override int getNumberOfComponents() {
    int ret = UtilsPINVOKE.VecDataArray3uc_getNumberOfComponents(swigCPtr);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public unsafe void setValues(byte[] val) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray3uc_setValues__SWIG_0(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void setValues(byte[] val, int n) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray3uc_setValues__SWIG_1(swigCPtr, (global::System.IntPtr)swig_ptrTo_val, n);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public unsafe void getValues(byte[] val) {
    fixed ( byte* swig_ptrTo_val = val ) {
    {
      UtilsPINVOKE.VecDataArray3uc_getValues(swigCPtr, (global::System.IntPtr)swig_ptrTo_val);
      if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    }
    }
  }

  public static readonly int NumComponents = UtilsPINVOKE.VecDataArray3uc_NumComponents_get();
}

}
