//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Imstk {

public class VectorVectorPuncturePoint : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<VectorPuncturePoint>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorVectorPuncturePoint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorVectorPuncturePoint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VectorVectorPuncturePoint obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VectorVectorPuncturePoint() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UtilsPINVOKE.delete_VectorVectorPuncturePoint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VectorVectorPuncturePoint(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorPuncturePoint element in c) {
      this.Add(element);
    }
  }

  public VectorVectorPuncturePoint(global::System.Collections.Generic.IEnumerable<VectorPuncturePoint> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (VectorPuncturePoint element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public VectorPuncturePoint this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(VectorPuncturePoint[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(VectorPuncturePoint[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, VectorPuncturePoint[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public VectorPuncturePoint[] ToArray() {
    VectorPuncturePoint[] array = new VectorPuncturePoint[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<VectorPuncturePoint> global::System.Collections.Generic.IEnumerable<VectorPuncturePoint>.GetEnumerator() {
    return new VectorVectorPuncturePointEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorVectorPuncturePointEnumerator(this);
  }

  public VectorVectorPuncturePointEnumerator GetEnumerator() {
    return new VectorVectorPuncturePointEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorVectorPuncturePointEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<VectorPuncturePoint>
  {
    private VectorVectorPuncturePoint collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorVectorPuncturePointEnumerator(VectorVectorPuncturePoint collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public VectorPuncturePoint Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (VectorPuncturePoint)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public VectorVectorPuncturePoint() : this(UtilsPINVOKE.new_VectorVectorPuncturePoint__SWIG_0(), true) {
  }

  public VectorVectorPuncturePoint(VectorVectorPuncturePoint other) : this(UtilsPINVOKE.new_VectorVectorPuncturePoint__SWIG_1(VectorVectorPuncturePoint.getCPtr(other)), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    UtilsPINVOKE.VectorVectorPuncturePoint_Clear(swigCPtr);
  }

  public void Add(VectorPuncturePoint x) {
    UtilsPINVOKE.VectorVectorPuncturePoint_Add(swigCPtr, VectorPuncturePoint.getCPtr(x));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = UtilsPINVOKE.VectorVectorPuncturePoint_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = UtilsPINVOKE.VectorVectorPuncturePoint_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = UtilsPINVOKE.VectorVectorPuncturePoint_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    UtilsPINVOKE.VectorVectorPuncturePoint_reserve(swigCPtr, n);
  }

  public VectorVectorPuncturePoint(int capacity) : this(UtilsPINVOKE.new_VectorVectorPuncturePoint__SWIG_2(capacity), true) {
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  private VectorPuncturePoint getitemcopy(int index) {
    VectorPuncturePoint ret = new VectorPuncturePoint(UtilsPINVOKE.VectorVectorPuncturePoint_getitemcopy(swigCPtr, index), true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private VectorPuncturePoint getitem(int index) {
    VectorPuncturePoint ret = new VectorPuncturePoint(UtilsPINVOKE.VectorVectorPuncturePoint_getitem(swigCPtr, index), false);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, VectorPuncturePoint val) {
    UtilsPINVOKE.VectorVectorPuncturePoint_setitem(swigCPtr, index, VectorPuncturePoint.getCPtr(val));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorVectorPuncturePoint values) {
    UtilsPINVOKE.VectorVectorPuncturePoint_AddRange(swigCPtr, VectorVectorPuncturePoint.getCPtr(values));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorVectorPuncturePoint GetRange(int index, int count) {
    global::System.IntPtr cPtr = UtilsPINVOKE.VectorVectorPuncturePoint_GetRange(swigCPtr, index, count);
    VectorVectorPuncturePoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorPuncturePoint(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, VectorPuncturePoint x) {
    UtilsPINVOKE.VectorVectorPuncturePoint_Insert(swigCPtr, index, VectorPuncturePoint.getCPtr(x));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorVectorPuncturePoint values) {
    UtilsPINVOKE.VectorVectorPuncturePoint_InsertRange(swigCPtr, index, VectorVectorPuncturePoint.getCPtr(values));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    UtilsPINVOKE.VectorVectorPuncturePoint_RemoveAt(swigCPtr, index);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    UtilsPINVOKE.VectorVectorPuncturePoint_RemoveRange(swigCPtr, index, count);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorVectorPuncturePoint Repeat(VectorPuncturePoint value, int count) {
    global::System.IntPtr cPtr = UtilsPINVOKE.VectorVectorPuncturePoint_Repeat(VectorPuncturePoint.getCPtr(value), count);
    VectorVectorPuncturePoint ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorVectorPuncturePoint(cPtr, true);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    UtilsPINVOKE.VectorVectorPuncturePoint_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    UtilsPINVOKE.VectorVectorPuncturePoint_Reverse__SWIG_1(swigCPtr, index, count);
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorVectorPuncturePoint values) {
    UtilsPINVOKE.VectorVectorPuncturePoint_SetRange(swigCPtr, index, VectorVectorPuncturePoint.getCPtr(values));
    if (UtilsPINVOKE.SWIGPendingException.Pending) throw UtilsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
